### ISSUE TITLE
Give warning on `projectdir` if project is standard Julia project

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DrWatson.jl#10]
if there is a way to consistently tell if the current project is the "julia default" (whatever that means) then we should warn when the function `projectdir()` is called and showing the default dir.

**Comment by asinghvi17** [comment]
`Base.active_project()` and knowing the current directory path could help?

Also, for most people, the active project is in `~/.julia/environments/$(string(VERSION.major) * "." * string(VERSION.minor))`

**Comment by Datseris** [comment]
We can compare `projectdir()` with the directory you paste here.

My only problem is that I don't really know how "stable" is the path you cite. But still, given that this will only throw an warning (and not error) maybe its a good starting point!

**Comment by asinghvi17** [comment]
`Base.active_project() == Base.load_path_expand("@v#.#")` from @fredrikekre on Slack
