### ISSUE TITLE
Make `quickactivate` do nothing if the project is already active.

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DrWatson.jl#109]
I find it ridicoulous to be constantly spammed with
```
Activating environment at `C:\Users\datseris\ownCloud\MyScience\Projects\Klein Tunneling in Graphene\kwant_graphene\Project.toml`
```
when this project is already active...

I personally find `quickactivate` super convenient, so every script I ever write starts with this function.

Maybe it is a good idea to make it do nothing if the project-to-be-activated is already active? Or maybe there is some drawback in this?

So what I am asking is whether there is any benefit whatsoever into activating again the already active project.

**Comment by sebastianpech** [comment]
Good idea. Also annoyed me.
No benefit. Activate just resolves the load path, sets `Base.ACTIVE_PROJECT` and checks if that worked.

**Comment by Datseris** [comment]
A developer of Pkg confirms that there is no benefit: https://github.com/JuliaLang/Pkg.jl/issues/1452

They also suggest that we could use `NullLogger`, but I'd like to keep the message of activation if the activated project is indeed new. So we should just put in a quick if statement checking `Base.active_project()`.

**Comment by fredrikekre** [comment]
(Missed opportunity for naming the function `quacktivate` :slightly_smiling_face: ).
