### ISSUE TITLE
Keyword problem with `@tagsave`

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DrWatson.jl#111]
I am doing
```
@tagsave(datadir("husimi_$(fname).bson"), @dict Q1 Q2 r0s ks1 ks2 σ; storepatch=false)
```
which gives:
```

ERROR: MethodError: no method matching tagsave(::String, ::Dict{Symbol,Any}, ::String, ::Bool, ::LineNumberNode; storepatch=false)
Closest candidates are:
  tagsave(::Any, ::Any, ::Bool, ::Any, ::Any) at deprecated.jl:65 got unsupported keyword argument "storepatch"
  tagsave(::Any, ::Any, ::Bool, ::Any, ::Any, ::Any) at deprecated.jl:65 got unsupported keyword argument "storepatch"
  tagsave(::Any, ::Any, ::String) at deprecated.jl:65 got unsupported keyword argument "storepatch"
  ...
```

But using directly `tagsave` works. 

@sebastianpech I think at some point you mentioned that we have to remove non-keyword versions. Is this the time to do it?

**Comment by sebastianpech** [comment]
I don't remember tbh. I'll have a look at it later

**Comment by sebastianpech** [comment]
The problem appears to be the `;`. I asked on slack for more info about macro invocation with `;`, let's see.
```
julia> macro foo(ex...)
           ex
       end
@foo (macro with 2 methods)
julia> @macroexpand @foo(1,2,3)
(1, 2, 3)
julia> @macroexpand @foo(1,2;3)
(:($(Expr(:parameters, 3))), 1, 2)
```
So this `@tagsave(datadir("husimi_$(fname).bson"), (@dict Q1 Q2 r0s ks1 ks2 σ), storepatch=false)` should work.

**Comment by sebastianpech** [comment]
It's not the macro invocation:
```
julia> dump(:(1,2;3,3,4,foo=1))
Expr
  head: Symbol tuple
  args: Array{Any}((3,))
    1: Expr
      head: Symbol parameters
      args: Array{Any}((4,))
        1: Int64 3
        2: Int64 3
        3: Int64 4
        4: Expr
          head: Symbol kw
          args: Array{Any}((2,))
            1: Symbol foo
            2: Int64 1
    2: Int64 1
    3: Int64 2
```
Should we support that input format? Don't know if having `;` in a matrix call is considered julian

**Comment by Datseris** [comment]
Sorry @sebastianpech I got a bit lost. First of all, the problem was that I used `;` for the keyword call. Okay.

`;` is indeed used to make matrices I can vouch for that. But on the other hand I use exclusively `;` instead of `,` to separate keyword arguments, both in function definition as well as function call. But I don't know what is the general consencous. How do you go about it?

Are you proposing to support the possibility of doing `@tagsave(a, b; storepatch = false)` ?

**Comment by sebastianpech** [comment]
> Are you proposing to support the possibility of doing @tagsave(a, b; storepatch = false) ?

Yes. So it's like calling a function with with keyword arguments, where it doesn't matter if you use the `;` or not.

**Comment by Datseris** [comment]
Well for me the vote is clear: I vote yes, since this is the syntax I use :P

**Comment by Datseris** [comment]
@sebastianpech these are the deprecation warnings I think we should remove:

https://github.com/JuliaDynamics/DrWatson.jl/blob/5fb3d2fca926951d73154dec1d56262a23d1ea3a/src/saving_tools.jl#L308-L311

**Comment by Datseris** [comment]
Also, what we are discussing here, seems like functionality that could/should exist on MacroTools.jl (about parsing keywords)

**Comment by sebastianpech** [comment]
There is also:

https://github.com/JuliaDynamics/DrWatson.jl/blob/87a0a3bf2d6870fa4f1fd4a47cd8ef1078689688/src/saving_files.jl#L209

and we still have the one from scriptsdir

https://github.com/JuliaDynamics/DrWatson.jl/blob/476883bc4337678b318c517bbc10c8dbe1eb8b54/src/project_setup.jl#L8

> Also, what we are discussing here, seems like functionality that could/should exist on MacroTools.jl (about parsing keywords)

Maybe. Do they have that in MacroTools?

**Comment by Datseris** [comment]
I actually don't know... I am such a macro NOOB that I can't really say anything. I just know that that package exists, and seemed reasonable that it could accommodate such functionality.
