### ISSUE TITLE
Relevant software

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DrWatson.jl#113]
We should add a "relevant software" section into the documentation, that lists useful things, related to managing or using a scientific project. Add your suggestions and I'll add them to the list!

### Efficient code writing
* Parameters.jl
* https://github.com/docopt/DocOpt.jl
* https://github.com/vtjnash/Glob.jl

### Presentation in various formats, Documenting your code
* IJulia
* Literate.jl
* Weave.jl
* Documenter.jl

### Debugging, writing code
* Juno
* Revise.jl, especial `includet`
* Debugger.jl 

### Performance measures
* ProgressMeter.jl 
* BenchmarkTools.jl
* https://github.com/KristofferC/TimerOutputs.jl
* ProfileViews (also available in Juno)

### Saving Data
* BSON.jl
* JLD2.jl
* CSV.jl

### Data management & data bases
* https://github.com/helgee/RemoteFiles.jl
* https://github.com/JuliaDynamics/CaosDB.jl
* https://juliadb.org/
* https://github.com/SebastianM-C/StorageGraphs.jl

### Tabular data
* https://juliadata.github.io/DataFrames.jl/stable/
* https://www.queryverse.org/

**Comment by sebastianpech** [comment]
Revise.jl and specifically `includet`

**Comment by sebastianpech** [comment]
Weave.jl and Literate.jl
ProgressMeter.jl maybe

**Comment by tamasgal** [comment]
Docopt.jl, BenchmarkTools.jl

**Comment by sebastianpech** [comment]
DrWatson.jl ... Oh wait

**Comment by sebastianpech** [comment]
Debugger.jl (I like the repl interface a lot more than the Juno debugger)

**Comment by sebastianpech** [comment]
- BSON.jl
- JLD2.jl
- CSV.jl
- ...

**Comment by Datseris** [comment]
Oh yeah, the savedata packages. I am curious, which package do you guys use to save your data?

**Comment by sebastianpech** [comment]
Depends. Config files JSON or TOML. Small datasets maybe also outside of Julia DelimitedFiles or CSV. Larger stuff BSON or FortranFiles. I like BSON a lot because until now I never had problems with saving custom types and such. I remember in the beginning of JLD I often had to write custom serializers.

**Comment by sebastianpech** [comment]
GLOB.jl

**Comment by sebastianpech** [comment]
@Datseris Regarding your comment about file size. Last Juliacon there was a talk about https://github.com/rofinn/FilePaths.jl/blob/master/README.md. I'm not sure if it's a hugh improvement over the functions in base. 

Also about traversing directory trees: There is a neat example code in AbstractTrees https://github.com/Keno/AbstractTrees.jl/blob/master/examples/fstree.jl

**Comment by sebastianpech** [comment]
https://github.com/helgee/RemoteFiles.jl

Never used it, but always liked the idea.
