### ISSUE TITLE
Tree view of a folder with file sizes

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DrWatson.jl#115]
It would be quite beneficial to be able to create a tree like view of a folder and its subfolders, but also while displaying the size of the files. (I personally would be using this to view my data folders, but it is useful generally).

I think this can be done by extending the code already existing here: https://github.com/Keno/AbstractTrees.jl/blob/master/examples/fstree.jl 

which at the moment outputs:
```
z1wBY
├─ .gitignore
├─ .travis.yml
├─ examples
│  └─ fstree.jl
├─ LICENSE.md
├─ README.md
├─ REQUIRE
├─ src
│  ├─ AbstractTrees.jl
│  ├─ implicitstacks.jl
│  └─ traits.jl
└─ test
   └─ runtests.jl
```

for the folders their size could be the sum of the size of the subitems.

**Comment by Datseris** [comment]
[`Base.stat`](https://docs.julialang.org/en/v1/base/file/#Base.stat) gives the file size, but in bytes. One should convert it to a more readable form.

**Comment by sebastianpech** [comment]
Also for a proper implementation one should check for permissions. The problem with showing the foldersize is always that you can't know it if you can access all files.

Shouldn't be a problem with DrWatson though

**Comment by sebastianpech** [comment]
However, I'm not certain that this is something that should be in DrWatson. Why not use a file explorer?  Most editors have on embedded. Also if you're in the repl, c-z paused it then you can use e.g. tree and then get your repl back with fg.

**Comment by Datseris** [comment]
It's a good question whether it should included in DrWatson or not.

But at least on Windows I am not aware of something that does what is described here. On Windows `tree` in the console does print the tree successfully but no file sizes. The file explorer does print file sizes but only for files, not for folders.

**Comment by sebastianpech** [comment]
Printing folder sizes can be problematic. `ls` for example also doesn't show them. Depending on how deep your folders are nested it can take very long to obtain the folder size. On linux or mac I often use du. There is also ncdu which has a ncurses TLI.

For example running ncdu in my home folder on our institut cluster takes an hour

**Comment by Datseris** [comment]
oh, okay, I see. I guess I was overly naive when opening this :D

**Comment by sebastianpech** [comment]
It's easy to implement but usage can be problematic in some cases

**Comment by Datseris** [comment]
Yes, that's why I closed the issue... DrWatson is supposed to stop nightmares , not bring new ones :D :D :D
