### ISSUE TITLE
Argument order for `produce_or_load`

### ISSUE THREAD

**Issue by xukai92** [JuliaDynamics/DrWatson.jl#126]
It might be nice to move the function argument `f` as the first agument of `produce_or_load` so people can use the `do` keyword instead of defining the function explicitly

```julia
N = 2000; T = 2000.0
file = produce_or_load(
    datadir("mushrooms", "toy"), # path
    @dict(N, T), # container
    prefix = "fig5_toyparams" # prefix for savename
) do d
    HTEST = 0.1:0.1:2.0
    WS = [0.5, 1.0, 1.5]
    @unpack N, T = d
    toypar_h = [[] for l in HS]

    for (wi, w) in enumerate(WS)
        println("w = $w")
        for h in HTEST
            toyp = toyparameters(h, w, N, T)
            push!(toypar_h[wi], toyp)
        end
    end
    return @dict toypar_h
end
@unpack toypar_h = file
```

**Comment by asinghvi17** [comment]
Looks like it would be as simple as defining:
```julia
produce_or_load(f::Function, c) = produce_or_load(c, f)
produce_or_load(f::Function, p::String, c) = produce_or_load(p, c, f)
```
?

**Comment by Datseris** [comment]
Yes seems to be that simple. @xukai92 if you test this extention and it works, we should put it in the docs! Seems to be a nice convenient syntax!

**Comment by xukai92** [comment]
It actually works nicely with an extra `; kwargs...` in all function calls.

> Unfortunately changing the order of arguments without this dispatch example is a breaking change ...

What does this mean?

**Comment by Datseris** [comment]
You (meaning "we", the developers) cannot change the order of the arguments of a function used by users. It will break their code. Anyone that uses `produce_or_load` will have a code that doesn't work if we just change the order of arguments around.

**Comment by xukai92** [comment]
Oh I see. You mean **without** the dispatch. Is it OK to just add the dispatch version then? Seem to solve the problem by itself.

**Comment by Datseris** [comment]
I think adding the dispatch is _probably_ fine. It will create ambiguity errors though when users pass `c <: Function` into `produce_or_load`. It is possible to create custom structs and subtype them as functions.

If you want to open a PR about this, we should test what happens in this scenario where a user tries to use a `c <: Function`.

**Comment by xukai92** [comment]
What's the status of 2.0? Is this too late to add this change (or it's already there)?

**Comment by Datseris** [comment]
Feel free to firstly open a PR that uses multiple dispatch to keep the old method working as is, but allow the `do` format to be used in the new syntax. Then, on this PR we can discuss breaking scenarios and see how to proceed with merging.

**Comment by xukai92** [comment]
I fired a PR in #227.
