### ISSUE TITLE
Add quickmention to docs about "mycustomdir()" functions

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DrWatson.jl#128]
Following #122 it is clear (at least for me) that we should not offer customization on `initialize_project`, for two reasons:

1. `datadir()` and company rely on the exact, hardcoded structure of `initialize_project`.
2. It is one of DrWatson's main purposes to provide a well-thought out project structure out of the box.

That being said, we should document how easy it is to implement custom `mypreferreddir()` functions in the docs. It is as simple as: `mynewdir(args...) = projectdir("mynewdir",args...) `

**Comment by xukai92** [comment]
As a side note, one issue of this approach is that one need to add this definition to each file or script that needs to use it.

**Comment by sebastianpech** [comment]
Not if you define the project as a package https://juliadynamics.github.io/DrWatson.jl/dev/real_world/#Making-your-project-a-usable-module-1

**Comment by sebastianpech** [comment]
@Datseris Maybe we could offer a macro for defining those functions. So the package file could look something like this
module AlbedoProperties

```
using Reexport
@reexport using Dates, Statistics
@newdir "mynewdir"
end
```

Which expands to
```
export mynewdir
mynewdir(args...) = projectdir("mynewdir",args...)
```

**Comment by sebastianpech** [comment]
Though I don't know how important it is to have this functionality implemented in DrWatson. We should't overload it it think.

**Comment by Datseris** [comment]
> As a side note, one issue of this approach is that one need to add this definition to each file or script that needs to use it.

That is true. But the alternative would be to allow an unlimited number of these functions though, which I can't agree that is useful... For example one could also argume that `simsdir(args...) = datadir("sims", args...)` could exist as well, but there is no end to that.

@sebastianpech Haha! You just wrote this 2 seconds before me! I was about to write "thankfully we have a macro expert working here, which could provide a macro to make this process easier" with a macro exatly like the one you wrote.

The thing is however, that immdiatelly after you wrote the macro, I realized that there is no benefit than the user themselves just defining... `mynewdir(args...) = projectdir("mynewdir",args...)` . Like, its still one line of code, and it is actually much clearer than the macro.

**Comment by sebastianpech** [comment]
I like macros :), but yeah you right.

> Like, its still one line of code, and it is actually much clearer than the macro.

Don't forget the `export` ;) so twice as much
