### ISSUE TITLE
Base.ntuple vs DrWatson.@ntuple

### ISSUE THREAD

**Issue by crstnbr** [JuliaDynamics/DrWatson.jl#129]
Maybe you're already aware of it but it is a bit confusing that your `@ntuple` creates a `NamedTuple` while `ntuple` in Base creates a regular `Tuple`.

Perhaps renaming your `@ntuple` to `@nt`, `@namedtuple`, or `@NT` (which is how NamedTuples.jl called it) could improve the situation. What do you think?

**Comment by Datseris** [comment]
I (personally) think that this is not important enough to increment major version number. (you realize that this is a breaking change, right?)

**Comment by crstnbr** [comment]
I do and I agree that this alone wouldn't justify a new major version. Nonetheless I'd consider doing it in the new major version (put it on a virtual milestone).

**Comment by Datseris** [comment]
*(I close because I want to have an overview of relevant issues when going to the Issues page. I don't foresee a 2.0 version for years at the moment. Once this time comes, this will be already under the milestone)*
