### ISSUE TITLE
Start documentation by flashing a minimal example

### ISSUE THREAD

**Issue by crstnbr** [JuliaDynamics/DrWatson.jl#131]
I've just worked myself through the documentation to learn more about DrWatson and to decide whether I want to use it in the future.

IMHO it would make sense to flash a minimal example of the entire workflow of the package right at the beginning of the docs (after Introduction) to give a quick first overview. It could show how to initialize a scientific project, run sum simulations, save the results and perhaps run some more simulations with an extra parameter or so. Short and simple, not too much explanation.

For further information people can checkout the individual sections of the docs (I like the structure!) like the "Real World Examples".

**Comment by tbeason** [comment]
I agree with this. I'm looking through the docs now, trying to get started, and *in theory* I understand. I've created a couple of projects, some of them even have modules in `src` which previously I was developing in a separate folder (nice to keep things together though). But the proper sequence of steps for committing code/producing results/saving results does trip me up a bit. Like I understand the functions involved, but a showcase of the "expected" workflow would be really helpful.

**Comment by Datseris** [comment]
I'll see if I can put something together, although I'd much rather that this contribution comes from someone else but me. I see things very different from a beginner, I've been along the ride of this project from the very start, and thus it is difficult for me to put myself in the eyes of a beginner. If I can sketch out something nice I'll open a PR or so.

> But the proper sequence of steps for committing code/producing results/saving results does trip me up a bit.

I think you will be much less confused if you don't think that DrWatson has a "specific sequence of steps you should follow". I don't think of it this way, I think of it like this: I use the parts of DrWatson that are useful for my project at the time I need them. Besides the `datadir()` ,etc. functions, which I of course use in every script, there is no other part of DrWatson that I am "guaranteed" to use in a specific sequence from the start of the script to the end.

But thinking about this more, I think I get your points: you want someone experienced to "briefly showcase" how they use DrWatson?

**Comment by tbeason** [comment]
> But thinking about this more, I think I get your points: you want someone experienced to "briefly showcase" how they use DrWatson?

Absolutely. The documentation is very thorough about what each function/macro does. Typically that would be enough. But this isn't a regular Julia package, so there needs to be just that little bit extra.

**Comment by Datseris** [comment]
Hi @tbeason and @crstnbr , could you please have a look at this page: https://juliadynamics.github.io/DrWatson.jl/previews/PR143/workflow/ and tell me what you think?

**Comment by tbeason** [comment]
Looks good

**Comment by crstnbr** [comment]
I agree, looks great!

**Comment by tamasgal** [comment]
That’s really nice!
