### ISSUE TITLE
Path separator is OS-specific. Should it be?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DrWatson.jl#132]
In PR #66 (cc @tamasgal ) we added the `PATH_SEPARATOR` variable, https://github.com/JuliaDynamics/DrWatson.jl/blob/46e7cceb7c25e2eb21abf059e6b3fb6ad7fe33e7/src/DrWatson.jl#L5 but this variable is OS-specific. In windows it only works if you do `"data\\"` and not if you do `"data/"`. This is not how Base Julia behaves though. For base Julia both `data\\res` and `data/res` will count as changing directory. 

I think we should change this `PATH_SEPARATOR` viariable to be like base Julia, because the problem now is that doing `savename("data/", s)` on windows returns `data_a=3` instead of the correct `data\\a=3`.

**Comment by tamasgal** [comment]
Oh, well the intention was "to be OS specific" 😅  I am not sure if I understand correctly. Is the path separator on windows an escaped backslash? I mean, is the "hack" we determine the path separator the problem since it assumes it's only one character?

**Comment by Datseris** [comment]
I wasn't remembering whether it was intentional or not...

The path separator in windows is indeed `\\` in Julia. In the other two OS it is `/`. In base Julia, if you do `cd("data/res")` or `cd("data\\res")` both commands will bring you to the `res` directory. Julia doesn't really care.

> Edit: I am also not sure if doing savename("data/", s) should be encouraged. I thought the main point was to get rid of all the hardcoded path separators in user-code 🤔

You are right, this is important and it may have been one of the main reasons that we did this change. However, the docstring of `savename` does state that "connector is not added if `prefix` ends with a separator". But this is not in fact true, as e.g. in Windows Julia counts both `\\` and `/` as separators. I would expect given this statement that `savename` would behave like how Julia handles path separators.

I don't think that fixing this issue would "encourange manual path separators". I think we've done a lot of progress to encourange people to not do this throughout the docs. But I personally count what is happening here as a bug, not a feature.

**Comment by tamasgal** [comment]
Yes I see. I have never used `savename` to also include the path, I always use it inside e.g. `datadir("path", "to", "whatever", savename("prefix", ntuple))`.

I personally think that `savename` is just the filename and not the path, so I think it's better to stick to kind of this "single responisibility".

Of course I understand that the docs say something different and many people are probably already using it this way 😕 

What do you think?

**Comment by tamasgal** [comment]
To me also the description suggests that it should be used as a "name" and not (ab)used as a path: https://juliadynamics.github.io/DrWatson.jl/dev/name/#DrWatson.savename

But of course I now found the example with the leading `/`...

**Comment by Datseris** [comment]
To clarify: I also don't (typically) use paths in the `prefix` part and also use it in `datadir` stuff. I totally agree that this "single responsibility" is better. 

But as you just noticed, the docs do mention this, and it is also in the example as well as the test suites. So the options would be to remove this alltogether or to fix what this issue is about.

We can't remove this functionality from the code as this is not only breaking, but also "hardcore-breaking", as e.g. files won't be able to be loaded in some scripts anymore. But we could simply remove this mentioning from the documentation.

**Comment by tamasgal** [comment]
Yes, I fully agree. Too bad that we forgot about that...

Not sure how to proceed, but removing it from the docs is probably a good start.

What do you think about a deprecation warning via `if '\' in prefix || "//" in prefix`... and then put this onto the v2 milestone?

I am not sure how `PATH_SEPARATOR = "\\"` will behave. You are sure that it is not breaking? Or what is the exact change you propose?

**Comment by Datseris** [comment]
I like the depwarn idea. The fix is to simply define `PATH_SEPARATOR = ('/', '\\')` and modify the code to use `in PATH_SEPARATOR`.

**Comment by tamasgal** [comment]
OK I just had a quick look (sorry I was on mobile before). So this is where it happens (regarding this issue) https://github.com/JuliaDynamics/DrWatson.jl/blob/bd656df6d48aee639a291ad32af7a28f373ba1ad/src/naming.jl#L98

**Comment by tamasgal** [comment]
I had a closer look but I don't see an easy way of changing `PATH_SEPARATOR` into a list of chars since it is used in tests and it seems to pick up the correct one for *nix and Windows based systems.

Looking at this:

```juliaREPL
julia> mkpath(joinpath("a/b", "c\\d", "e/f"))
"a/b/c\\d/e/f"

shell> ls a/b/c
c\d/ c/
shell> ls a/b/c
c\d/ c/
shell> ls a/b/c
d

shell> ls a/b/c/d/e/f
ls: a/b/c/d/e/f: No such file or directory
```

It seems that mixing of paths is not working, so to me it seems that the user needs to use the same path separator as dictated by the system.

This means that the only thing we need to change is indeed this line: https://github.com/JuliaDynamics/DrWatson.jl/blob/bd656df6d48aee639a291ad32af7a28f373ba1ad/src/naming.jl#L98

**Comment by Datseris** [comment]
Let's just move with your suggestion of simply removing this from the docs and adding a depwarn if given path ends with `"\\"` or `"/"`? Then we don't have to actually fix this, since we don't want to have it anyway!

**Comment by tamasgal** [comment]
I just created https://github.com/JuliaDynamics/DrWatson.jl/pull/133
