### ISSUE TITLE
Workflow of DrWatson

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DrWatson.jl#141]
Hi guys,

I want to prepare(*) a short video going through a typical scientific workflow and how drwatson makes it very simple. I prepared the follow chart that I will be based on when making my video.

![workflow](https://user-images.githubusercontent.com/19669089/78612373-7949cb80-7869-11ea-8266-980c3487f7ec.png)

Do you agree, disagree, or have something to add? @tamasgal  (also @tamasgal  maybe accept the invitation to JuliaDynamics?)

(*) Unfortunately more and more people ask for this :(

**Comment by JonasIsensee** [comment]
Looks good!
Only comment: the itemlists are a bit small in my opinion. Maybe you could increase the font size a bit or alternatively make the spacing between lines bigger.

Btw. did I ever send you the slides to my DrWatson talk?

**Comment by sebastianpech** [comment]
Looks good. Maybe in 2. (don't know if you have that planned anyway) you could show the difference of `src`, `script` and the feature for loading defaults (`@quickactivate :name`). Though, the last one might be considered an advanced feature and not necessary for an intro video.

Honestly, I'm looking forward to this video as well. Really interested in how your workflow on those topics looks. ;)

**Comment by Datseris** [comment]
> Btw. did I ever send you the slides to my DrWatson talk? 

Yes, thanks a lot, they are very good. I used them a bit to plan this. 

For the sizes. The above figure is supposed to cover almost the entire widescreen (i.e. I will show this figure in "Full screen" mode). Do you think it still has small fonts? I've tried a different layout that allows a bit bigger, let me know:

![workflow](https://user-images.githubusercontent.com/19669089/78653652-ba6ec980-78c3-11ea-8062-8f68fae69246.png)

**Comment by JonasIsensee** [comment]
Ah, this second one is great! First one was good but I love this one. :)

**Comment by Datseris** [comment]
@sebastianpech sorry, forgot to reply! Yes, I plan to show different versions, probably `projectdir, datadir, scriptdir` will be the ones I'll show. And I also agree, `@quickactivate :name` is probably too advanced... I want to try to keep this video 15 minutes or below, yet this seems an impossible task... Let's see!
