### ISSUE TITLE
Bring @unpack and @pack in drwatson

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DrWatson.jl#147]
I only use Parameters.jl for `@unpack` and sometimes `@pack!` and now these are in a solo package:

https://github.com/mauro3/UnPack.jl/blob/master/src/UnPack.jl

I vote to bring them here by copying the source and exporting the two macros as well.

**Comment by tamasgal** [comment]
Why not just use that package and export their macros?

Btw. I use quite a few things from `Parameters.jl` ;)

**Comment by sebastianpech** [comment]
I also use quite a lot of the features from `Parameters.jl`. However, with `UnPack.jl` you can get almost everything with `Base.@kwdef`, except the `@assert` calls I think.

Same question as @tamasgal 
> Why not just use that package and export their macros?

**Comment by Datseris** [comment]
>  Why not just use that package and export their macros?

not 1.0.......

If you mean why not use in my personal projects, well, that is one more `using` statement, but also I think this functionality fits perfectly with all the `@dict, @ntuple, struct2dict` business we have.

**Comment by sebastianpech** [comment]
> not 1.0.......

I don't get it. 1.0 DrWatson or julia? 
Because `UnPack.jl` is compatible

https://github.com/mauro3/UnPack.jl/blob/e6b98bb08409b40605ca710b8be2733c90b384d9/Project.toml#L7

**Comment by Datseris** [comment]
Sorry, I was unclear. I am actively trying to not have packages with version less than 1.0 as dependencies, in both personal scientific projects as well as packages I develop. If there is something as simple as 100 lines of code, I see much more benefit and ease-of-mind to just copy it. 

I mean, if we can't do that, what's the reason to use all these MIT licenses...?

**Comment by tamasgal** [comment]
I don't get it. v0.1 is just a number, why is it bad that it's not 1.0? You can even fix the dependency to exact that version if you fear that v0.2 might break everything.

MIT is primarily partial source code reuse, it allows to package the software and redistribute it (e.g. as a Docker image). I don't see a valid reason why one should extract the code in this case, to me it's more code duplication and double maintenance in future.
Btw. it's also not only the actual code but also the corresponding tests.

**Comment by sebastianpech** [comment]
> I don't get it. v0.1 is just a number, why is it bad that it's not 1.0? You can even fix the dependency to exact that version if you fear that v0.2 might break everything.

Yeah. Can't you just add a compat entry for 0.1? That's basically like porting the exact same code

**Comment by sebastianpech** [comment]
Though, maybe that isn't possible if you have a second package that enforces another version. I think you can only have on version per Manifest file. But I'm not sure, haven't used the compat part of the `Project.toml` much

**Comment by Datseris** [comment]
Doesn't matter guys, I've convinced the author to release 1.0. We don't share the same view on versions and what they mean. For me "v0.1" is not at all just a number, because I adhere to https://semver.org/ . 

With Julia 1.0 and the new package manager it is spectacularly clear to me that packages not in 1.0 create problems. Every time I update I see downgrades here and there because someone somewhere in the list of 100s of dependencies didn't change a `0.5` to a `0.6`. And honestly, I don't blame them it is extremely hard to change every god damn dependency's minor version number. But still, what if in one of these 10s or 100s downgrades that happen with each update, there is an actual breakage? With 1.0 I don't have to worry about breakage. It is a peace of mind thing. As long as we follow symver and as long as I only use packages with version 1, I will never ever have to worry about breakages.

It gets even worse with Julia 1.0 and its new package manager: it clearly supports major versioning, since from the package manager's perspective version 0.6 is incompatible with 0.7. As  person that develops and maintains around 20/30 registered Julia packages, for me it is a pain in the ass to always worry about versions 0.x -> 0.x+1 because they "could" be breaking but in reality most authors treat them as just minor releases of a 1.x -> 1.x+1 thing. 

Besides, as package authors, I think people should have some moral responsibility. Version 0.x by definition means "the API of the package is not stable". If you have people _depending_ on your package you absolutely should have a version 1.0. If not, something doesn't sits right with this at least for me.

> MIT is not primarily partial source code reuse, it allows to package the software and redistribute it (e.g. as a Docker image). 

The only rules and guidelines of what an MIT license is for and what it is not for are written within the license, nowhere else. These are very much legal things so in my eyes there cannot be such a thing as "common practices". We read the license and we can decide for ourselves whether what we want to do with it is possible. For me, its clear that if I want 100 lines of code from a package of 10,000 loc, and the code is MIT licensed, I certainly can copy the code and the license if I don't want to bother with following versions and/or installing eeeeeeverything else from the given package. For my personal projects that is of course. This adheres perfectly to the MIT license of the code, unless I have misunderstood something about it!

**Comment by Datseris** [comment]
Ah something else:

> You can even fix the dependency to exact that version if you fear that v0.2 might break everything.

If I do that, **everyone** that has DrWatson installed will never be able to install version 0.2 of that package.

**Comment by tamasgal** [comment]
I think this shifted to a meta discussion ;)

If you fix the version and someone else is having problems because 0.2 came out, they will ping you and you can verify. 

I think the main difference between our views is how we evaluate the reliability of semver.
In an ideal world, everyone uses semver and respect it (that would be nice). In reality, it’s not the case. You have to check every release of every dependency. For this I use extra CI jobs which checks updated dependencies (I work on other large python projects with hundreds of deps and its a constant annoyance, no matter if 1.x or 0.x)

Btw. I am still against code copy in the sense that if a package has 10000 SLOC and only 100 are interesting, the package should be split. Code duplication is in my opinion worse. If that package is loaded and DrWatson would implement their own functions, we would get a warning due to Redefinition. That will cause confusion too...

Anyways, as always, there are different perspectives and there is no right one, the key is to define the weights if the pros and cons.

In that sense, since the dep is now 1.0, I think that we all are happy. 😉 

<img width="278" alt="C7DE0F35-CE07-46A6-B048-1BAAC7A6EA57" src="https://user-images.githubusercontent.com/1730350/81351338-61fa3a00-90c4-11ea-8bf7-3bcddd52a769.png">


![](https://imgs.xkcd.com/comics/workflow_2x.png)
