### ISSUE TITLE
collect_results! adds already existing entries

### ISSUE THREAD

**Issue by nmheim** [JuliaDynamics/DrWatson.jl#154]
Hi and first a big thank you for this package! It has made my life a lot easier! :)
I hope its ok for me to just open an issue here.

When I try to `collect_results!` existing entries are added to the results dataframe.
It looks to me like this happens because `names(df)` returns an array of strings and not symbols in this line:
https://github.com/JuliaDynamics/DrWatson.jl/blob/1089ea6a72555eb64043a0d820310ffc98f6dd5f/src/result_collection.jl#L93

So using `"path" in names(df)` fixed it for me. I am on Julia 1.4

**Comment by Datseris** [comment]
This _must_ be because of the latest DataFrames.jl update. Urgh, how I hate these non-1.0 packages. 

I think now dataframes makes the column names Strings instead of Symbols.

**Comment by Datseris** [comment]
@nmheim 

>  I hope its ok for me to just open an issue here.

Of course it is! And also feel free to open a PR with the fix! You become a contributor this way!

**Comment by Datseris** [comment]
@sebastianpech , @tamasgal by the way, these kind of situations are exactly what I was talking about in #147.

**Comment by nmheim** [comment]
> @nmheim
> 
> > I hope its ok for me to just open an issue here.
> 
> Of course it is! And also feel free to open a PR with the fix! You become a contributor this way!

Ok, great, will do! :)
