### ISSUE TITLE
git error in initialize_project 

### ISSUE THREAD

**Issue by dahtah** [JuliaDynamics/DrWatson.jl#167]
On my setup initialize_project fails with: 
```
ERROR: GitError(Code:ENOTFOUND, Class:Config, config value 'user.name' was not found)
```
which occurs here in the code
```
 git && LibGit2.commit(repo, "Initial commit")
```
Maybe add user_name as a keyword argument in initalize_project or prompt user for name?

**Comment by JonasIsensee** [comment]
Oh, this is interesting.
I'm not sure whether I agree with your suggested solution, though.
Apart from the repo initialization DrWatson does not let interact with git directly. 
So maybe it would be more appropriate to print a better error message instead of adding the complexity of handling possible git errors.

**Comment by sebastianpech** [comment]
How are you using git? In my opinion setting up your username and email ist part of the installation of git.

For example it's contained in the getting started section in  Pro Git.
https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup

**Comment by dahtah** [comment]
I'm no git expert, so perhaps there's a better solution, but since I have a different user name on github and various gitlabs, I set it locally in each repos. Maybe I'm an outlier here.

**Comment by dahtah** [comment]
Currently there's no work-around I can think of, aside from git=false. Can't set user name without git init first, but if you do that initialize_project complains that the directory is not empty or erases everything

**Comment by sebastianpech** [comment]
Ok that makes sense.
We could, instead of throwing the error, just show a warning. This way you can manually init the repo afterwards.

Thought we should add additional warnings for all git related stuff like tag if the repo was never initialized.

**Comment by Datseris** [comment]
I'd like some justification on the following: Why isn't `git=false` already the solution...? We are already saying that the solution is "you initialize your own git repo" and this is already possible. Seems to me there is nothing to be done...?

> Thought we should add additional warnings for all git related stuff like tag if the repo was never initialized.

We already provide warnings if there is no git repo and return `nothing` or `missing`.
