### ISSUE TITLE
usage of quickactivate is tricky

### ISSUE THREAD

**Issue by JonasIsensee** [JuliaDynamics/DrWatson.jl#17]
Hey,
I noticed that the usage of `quickactivate` is tricky.

It can only work if the `DrWatson` is installed in both the local and global environment.
(The same goes for all other packages. 
In the scripts you gave me you load all packages before calling `quickactivate`.)
This is misleading. The packages will be loaded from the global environment
if installed. This may give you a wrong version of the same package.

**Comment by Datseris** [comment]
Yeah I have realized that but I don't know yet how to fix it. But wait. 

If you do:
```
using DrWatson
quickactivate(...)
using Package1
```
will `Package1` _still_ be loaded from the global enviroment? This would be wrong.

**Comment by JonasIsensee** [comment]
`Package1` will be loaded from the just-activated environment.
If it is installed globally but not in the local project it will error.

**Comment by Datseris** [comment]
Okay then this is fine for now. It was my mistake to load packages before using `quickactivate`. At the moment I do something like:
```julia
using DrWatson
quickactivate(@__DIR__, "MagneticBilliardsLyapunovs")
using DynamicalBilliards, Statistics
```

I do not know if it is at all possible to use `quickactivate` _and_ use `DrWatson` from the current project. I also don't know what happens with loaded modules that one then changes project and loads them again. Does the old module get replaced? E.g. if:
```julia
using DrWatson
quickactivate(path)
using DrWatson
```
If the project in `path` has a _different_ version of `DrWatson` specified, what happens? I'll ask and learn soon.

**Comment by JonasIsensee** [comment]
AFAICT modules do not get replaced after changing the module and calling
`using MyModule` again but you should certainly ask someone who knows,
or test it.

**Comment by Datseris** [comment]
crossref: https://discourse.julialang.org/t/activating-a-project-with-modules-already-in-use/21222

**Comment by Datseris** [comment]
I have added a long warning message in the documentation string of `quickactivate`: https://juliadynamics.github.io/DrWatson.jl/dev/project/#DrWatson.quickactivate

To the best of my knowledge it is in fact _not_ possible to reload a module without some hacky way. Therefore I don't know if it is at all worth it for us to consider if somehow one can *both* use `quickactivate` and have the DrWatson version of the activated project.

I am closing this until someone can find a way for this to happen, but I doubt it.
