### ISSUE TITLE
collect_results undefined unless DataFrames is added

### ISSUE THREAD

**Issue by tobydriscoll** [JuliaDynamics/DrWatson.jl#177]
I started a fresh REPL and followed the tutorial instructions to start a project. The `collect_results` function was undefined. 

I then added the `DataFrames` package and quit the REPL. After a restart, the `using` statement did run the definition of `collect_results`.

Presumably this is some kind of interaction or bug with `Requires` in the `__init__` method.

**Comment by Datseris** [comment]
![image](https://user-images.githubusercontent.com/19669089/87818218-82840480-c86a-11ea-9860-7b6ea81765b2.png)

You will only get the function if you do this.

**Comment by Datseris** [comment]
> Presumably this is some kind of interaction or bug with Requires in the __init__ method.

Wait. Can you explain further? Did you use `DataFrames` but still didn't get the function?>

**Comment by tobydriscoll** [comment]
No. I misunderstood the optional loading mechanism. There is no technical issue.

Worth noting, though--the DF requirement is clear in the later sections of the docs, but not in the tutorial, so a bonehead (at least one :) starting with that and no knowledge can get confused.

**Comment by Datseris** [comment]
Thank you for pointing this out, this was important!
