### ISSUE TITLE
Handle trailing slashes in collect_results!

### ISSUE THREAD

**Issue by lhupe** [JuliaDynamics/DrWatson.jl#181]
When the `folder` argument to `collect_results!` contains a trailing slash (e.g `/home/lhupe/coolresults/`), the default setting for `filename` breaks. The result file will be saved as `/home/lhupe/coolresults/results_.bson`. This has the unfortunate side effect that on the next run, `collect_results!` will create an entry for its own cache file.
While this is not a bug of `DrWatson `(the issue is with `Base.splitdir`, which naively splits paths on the final separator), it would be nice to account for this in the default definition of `filename` (e.g. using `rstrip(folder, '/')` to remove trailing slashes).

**Comment by Datseris** [comment]
Just to be clear here: A path to "X" ends with "X". So a path to a folder should end with the folder name, not with `/`. Why do you give the final `/`?

**Comment by lhupe** [comment]
Trailing slashes are commonly used for paths referring to directories (I guess the slash implies that the directory is not a leaf node of the file system), and a lot of software simply ignores them.

There are some applications where there is a semantic distinction (e.g. the file-copying tool rsync, where a source path with a trailing slash means "copy the contents of the source directory into the target directory", and one without a trailing slash means "copy the source directory into the target directory"), but I don't think this makes sense in this context (to be fair, this was three years ago and I haven't really used any DrWatson functions other than `dict_list` since then, so I might not have the strongest grasp on what the context is).

If you do decide to distinguish (or just not support trailing slashes), that's definitely worth mentioning prominently in documentation because it will surprise at least some of your users.
