### ISSUE TITLE
Including Julia packages/modules in src

### ISSUE THREAD

**Issue by josePereiro** [JuliaDynamics/DrWatson.jl#183]
`As started in Gitter`
Hi, I have a question related with DrWatson.jl [Including Julia packages/modules in src](https://juliadynamics.github.io/DrWatson.jl/stable/project/#Including-Julia-packages/modules-in-src-1) documentation section.
In the forth point says:

>dev the local path to ModuleName using the package manager: dev src/ModuleName. Notice that this command uses a local path, see this PR for more details.
>- If you don't care to make this module a Julia package, simply delete its .git folder: src/Modulename/.git.
>- If you do care about publishing this module as a Julia package, then it is mandatory to keep it as git-repository. What we recommend in this case is to ignore src/Modulename in your main project's .gitignore.

My concern is that in the second point "If you do care about publishing this module " the main project Manifest will not have a way to track which version of src/ModuleName is being used "What we recommend in this case is to ignore src/Modulename in your main project's .gitignore."

**Comment by josePereiro** [comment]
I think we should treat those packages like any other one, the researcher must add them to the main Project.toml and is responsable to keep it up to date

**Comment by Datseris** [comment]
Yeap, I agree.

**Comment by sebastianpech** [comment]
I'm not entirely sure what you mean. If you dev any package you track what you want right? An improvement over what's written in the docs is using submodules or subtrees. Im doing this quite often.

I've wanted to write this up for quite some time, I think there is also an open issue about that.

**Comment by josePereiro** [comment]
Yeah, submodules would help, but now you are decoupling the mechanism being used to ensure package reproducibility. One part using the Julia environment, which I prefer for Julia packages, and another part using git. It is less clear, I think...

**Comment by josePereiro** [comment]
> If you dev any package you track what you want right?
That's the problem, you are tracking anything if you dev the package and gitignore the source. Just as the docs are suggesting

**Comment by Datseris** [comment]
@josePereiro have a look at my commit, I think this is the most sensible solution.

**Comment by omerchiers** [comment]
Sorry to comment on this closed issue, but I don't really understand the current documentation:

> If one defines inside the src folder a file AlbedoProperties.jl and in that file define a module AlbedoProperties (notice that these names must match exactly the project name), then upon doing using AlbedoProperties Julia will in fact just bring this module into scope.

there is nothing about the dev command here. Written like this, for me at least the module is not brought into scope unless I do dev or modify LOAD_PATH.

Am I misunderstanding something?

**Comment by Datseris** [comment]
I think you are referring to the page: https://juliadynamics.github.io/DrWatson.jl/dev/real_world/#Making-your-project-a-usable-module-1

Well, sorry it didn't work for you, but for me it works if I follow the instructions on that page.

**Comment by omerchiers** [comment]
Thanks for your quick reply.
Yes indeed, that's the link to the page. I forgot to put that in my comment. Sorry for that.
The thing is, I followed exactly the instructions, and julia tells me:

```
ERROR: ArgumentError: Package Detectivity not found in current path:
- Run `import Pkg; Pkg.add("Detectivity")` to install the Detectivity package.
```
I don't really understand how these instructions from [ https://juliadynamics.github.io/DrWatson.jl/dev/real_world/#Making-your-project-a-usable-module-1]( https://juliadynamics.github.io/DrWatson.jl/dev/real_world/#Making-your-project-a-usable-module-1 ) can work considering julia's code loading mechanism.

Does DrWatson modify the LOAD_PATH somehow to include the src/ the folder?
Following the instructions from the error message above, means my module is a project with a Project.toml. 
I can do that of course, but this is not really what is written in the instructions. Or is it written somewhere else?

Sorry for all those questions, but I'm completely lost and I'm very interested in this functionality.
Thanks in advance

**Comment by Datseris** [comment]
First lets answer: Do you activate the project in this path? I think the way Julia works is that it "explicitly" includes the activated project path as a loading path.

**Comment by omerchiers** [comment]
> EDIT: Please open a new issue describing your problem, you will get even better support this way!

Done!
https://github.com/JuliaDynamics/DrWatson.jl/issues/248#issue-874538319
