### ISSUE TITLE
[FR]: Auto-completion in `projectdir` and co.

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DrWatson.jl#184]
I am aware that it is possible to "hack" Julia's autocompletion system, and this has been used in e.g. Juno. I don't know how though.

However, wouldn't it be amazing if you can type:

```julia
datadir("CERES", "<TAB>
```
and the available files in the subdir of data/CERES are shown?

**Comment by sebastianpech** [comment]
Yep! Duplicate though: https://github.com/JuliaDynamics/DrWatson.jl/issues/149 ;)
