### ISSUE TITLE
Add CONTRIBUTING.md or section to the docs

### ISSUE THREAD

**Issue by kescobo** [JuliaDynamics/DrWatson.jl#191]
See "Community Guidelines" section of [JOSS review](https://github.com/openjournals/joss-reviews/issues/2673):

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by Datseris** [comment]
Closed in https://github.com/JuliaDynamics/DrWatson.jl/commit/0d045ce77ad4d4bd97b607cce93c5ba88c616ae4
