### ISSUE TITLE
Weird behavior of dict_list

### ISSUE THREAD

**Issue by theogf** [JuliaDynamics/DrWatson.jl#199]
Hi!
When using `dict_list` I observed a weird behavior : some Ints are changed to Floats without any particular reason
Here is a MWE : 
```julia
 dict_list(Dict(
       :n => [1],
       :h => [10, 15, 20],
       :a => 0.01,))
#  3-element Array{Dict{Symbol,Float64},1}:
 Dict(:a => 0.01,:n => 1.0,:h => 10.0)
 Dict(:a => 0.01,:n => 1.0,:h => 15.0)
 Dict(:a => 0.01,:n => 1.0,:h => 20.0)
```
This is not happening for `:n =>1`
This is with julia 1.5.1 and DrWatson 1.16

**Comment by sebastianpech** [comment]
Ok, so my guess here is, that `vals` in https://github.com/JuliaDynamics/DrWatson.jl/blob/3ae4c2a4354bfce048a2062af470941b84526ebc/src/dict_list.jl#L104
is promoted to `Float64`. As an alternative, we would need to create the pairs one by one, to keep the original type, because `Dict` manages to do the proper promotion:
```
julia> Dict(:n=>1, :b=>1.0) # Keeps original types
Dict{Symbol,Real} with 2 entries:
  :b => 1.0
  :n => 1

julia> Dict([:b,:n].=>[1,1.0]) # Changes original types
Dict{Symbol,Float64} with 2 entries:
  :b => 1.0
  :n => 1.0
```
Pretty sure, that is the problem. If you add a field that results in a promotion to `Any` it works again:
```
julia> dict_list(Dict(
              :n => [1,2],
              :h => ["a", "b", "c"],
              :a => 0.01,))
6-element Array{Dict{Symbol,Any},1}:
 Dict(:a => 0.01,:n => 1,:h => "a")
 Dict(:a => 0.01,:n => 2,:h => "a")
 Dict(:a => 0.01,:n => 1,:h => "b")
 Dict(:a => 0.01,:n => 2,:h => "b")
 Dict(:a => 0.01,:n => 1,:h => "c")
 Dict(:a => 0.01,:n => 2,:h => "c")
```

**Comment by sebastianpech** [comment]
I think the simplest thing to do is to check the `eltype` of each key in the original dict and convert the values back in this line: https://github.com/JuliaDynamics/DrWatson.jl/blob/3ae4c2a4354bfce048a2062af470941b84526ebc/src/dict_list.jl#L105

**Comment by Datseris** [comment]
(yeah this should be fixed absolutely)

**Comment by sebastianpech** [comment]
This should work: ´dd = Dict(p=>convert(eltype(c[k],v)) for (k,v) in zip(keys(iterable_dict),vals))` will check it later

**Comment by theogf** [comment]
Thanks for the instantaneous fix :D

**Comment by Datseris** [comment]
Haha sebastian is really fast :D Don't forget to advertise DrWatson!
