### ISSUE TITLE
Automated generation of project based on a text file

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DrWatson.jl#2]
In my dreams, the function `initialize_project` somehow reads the project specification text file and then knows how to create the project.

This is great for documentation and consistency: the project specification text file `src/project_structure` is loaded and expanded into the documentation. The same file is used for project creation and thus everything is robust and consistent.

The question is, how to structure the project_structure file and how to read it in Julia to make this possible?

**Comment by taqtiqa-mark** [comment]
Thanks for putting effort into making Dr Watson.  It looks promising as a tool to allow various domains structure their projects in a way that best suits that domain.

Hope this helps.....

The current default is described in `src/defaults/project_structure.txt`
This could be:
1. Formatted as some TOML file
1. If there is:
   - no `some-valid-drwatson-layout.toml` given at the command line
   - no `.drwatson.toml` in the `~/.drwatson` or `~/` user-space folders
1. Parsed and used to create the folders
1. Saved in the project as `.drwatson.toml`

The current configuration would look like this:
```
#
# Note each entry in `project:dirs` must be a sub-table that belongs to 
# the `project` element above it
#
[[project]]
dirs = [  "data"
              "plots",
              "notebooks",
              "papers",
              "scripts",
              "src",
              "test"]
    files = ["README.md",
                "Manifest.toml",
                "Project.toml" ]
    [[project.data]]
     dirs = [ "sims",
                  "exp_pro",
                  "exp_raw"
     ]
    [[project.plots]]
     dirs = [ ""]
    [[project.notebooks]]
     dirs = [ ""]
    [[project.papers]]
     dirs = [ ""]
    [[project.scripts]]
     dirs = [ "" ]
     files = ["intro.jl"]
    [[project.src]]
     dirs = [ ""]
    [[project.test]]
     dirs = [ ""]
     files = ["runtests.jl"]
```

This way each domain could setup projects as best sits them.

**Comment by Datseris** [comment]
The suggestion is quite nice, since it allows for customization.

But one has to weight the cost carefully versus the added complexity. This TOML-based setup is significantly more complex than the current file `src/defaults/project_structure.txt`. As I have no knowledge of TOML or parsing TOML, is it possible to somehow transform this file into something a bit more familiar and a bit more tree like, like the `src/defaults/project_structure.txt`?

**Comment by asinghvi17** [comment]
We could use YAML, that's a bit more human readable (and the syntax lends itself better to trees IMO).  Yes, the parsing is a bit ugly, but it's pretty good for simplicity (at the user interface level, at least).  There's a YAML parser written in Julia here: https://github.com/BioJulia/YAML.jl
