### ISSUE TITLE
dict_list order changes on different machines

### ISSUE THREAD

**Issue by lhupe** [JuliaDynamics/DrWatson.jl#204]
The output order of `dict_list` is different on different devices.

## MWE
```julia
using DrWatson

d = Dict(
    :foo => [0.01, 0.05],
    :bar => [0.1, @onlyif(:foo == 0.01, 0.4)],
    :baz => Inf
)
simgrid = dict_list(d)

println.(simgrid)
```

produces 

```
Dict(:baz => Inf,:bar => 0.1,:foo => 0.05)
Dict(:baz => Inf,:bar => 0.1,:foo => 0.01)
Dict(:baz => Inf,:bar => 0.4,:foo => 0.01)
```
on one machine and
```
Dict(:baz => Inf,:bar => 0.1,:foo => 0.01)
Dict(:baz => Inf,:bar => 0.1,:foo => 0.05)
Dict(:baz => Inf,:bar => 0.4,:foo => 0.01)
``` 
on another. 

Both machines use the official Julia v1.5.2 binaries, but have different operating systems and hardware configurarions.

This appears to be an extremely arcane bug — e.g. I get identical results on both machines by changing `baz => Inf` to e.g. a finite float. I wouldn't be surprised if it's hard to reproduce.

**Comment by tamasgal** [comment]
Julia's `Dict` is not ordered, so this is definitely not an "arcane bug" 😉 I think it's more worrying that you rely on the order of something which does not give you a guarantee on that by design.

Let me ask differently: why do you need the exact same order?

There is also a Dict-like data structure  which gives you guaranteed order, called `OrderedDict` and available in https://github.com/JuliaCollections/DataStructures.jl

**Comment by tamasgal** [comment]
EDIT (deleted): sorry I misread -- long night of coding 😅

**Comment by Datseris** [comment]
Regardless, I am not sure whether this is a "bug"...? Also Lukas: why is it important for you? What's the application?

**Comment by tamasgal** [comment]
So in principle it does not count as a "bug" as there is no mentioning of any order (perseverance) in the docs: https://juliadynamics.github.io/DrWatson.jl/dev/run&list/#DrWatson.dict_list

**Comment by lhupe** [comment]
1) as far as I can tell (with `dump`), the representation of the dictionaries is identical for both machines.
2) yes, it's not an actual "bug" by definiton, but it would be nice if the output of the function were stable. I discovered this when playing around with some of my data, and I got quite a shock when the parameters stored in the data file did not match my expectations from the `dict_list`.

**Comment by Datseris** [comment]
Re 2: I don't understand this. If you use `dict_list` the way I do, then the parameters within the `dict_list` are saved in the file. ...?

**Comment by lhupe** [comment]
no, we don't use it the way you do — we don't save the results of `dict _list` because we usually don't need them again. Since our simulations take hours to run anyway, having every indivdual cluster job recompute the simgrid isn't really a big deal.
For analyis, we usually use `collect_results, but we are currently reworking our simulation code and trying some new things that we can't use our old analysis pipelines for, so  occasionally I have to improvise a bit.

I agree that, given that the order of `dict_list` is not guaranteed to be preserved, this approach is a bit risky and I'm probably going to change it for the future. But if you don't plan to alter the behaviour of `dict_list`, a warning in the docs would be nice.

**Comment by tamasgal** [comment]
> But if you don't plan to alter the behaviour of dict_list, a warning in the docs would be nice.

Sounds like a nice first PR 🙂

**Comment by Datseris** [comment]
> no, we don't use it the way you do — we don't save the results of dict _list because we usually don't need them again. Since our simulations take hours to run anyway, having every indivdual cluster job recompute the simgrid isn't really a big deal.

I still don't understand this. How can you tell which simulation is which if you don't save the input parameters? What does `collect_results` collect? It needs a way to differentiate the columns, which to my understanding are the input parameters, not the output...?

---

For me the best outcome would be to fix `dict_list` so that this doesn't happen at all. But I for sure have no idea how to do this. Jonas wrote the initial code but to my understanding its lowest level is just `map`.

**Comment by lhupe** [comment]
Our data files contain all relevant parameters, so there is no need for storing them externally.

**Comment by Datseris** [comment]
Looking at the source, line 64 of dict_list.jl, I see that we wrap everything in a `Set`. My bet is that this is what messes up things. `map` (I would assume) definitely preserves order.

@lhupe I don't have access to different machines that can reproduce this issue. If you can please help, can you try replacing this `Set` with `unique!`, which functionally does the same thing, and let us know?

**Comment by tamasgal** [comment]
Yes, `map` deserves the order. `Set` however is based on a hash table and like the entry ordering is based on the underlying baskets. The order is probably even mixed up once the internal algorithm is forced to resize and thus also rehash all entries.

**Comment by lhupe** [comment]
> @lhupe I don't have access to different machines that can reproduce this issue. If you can please help, can you try replacing this `Set` with `unique!`, which functionally does the same thing, and let us know?

with `unique!`, the order is identical for both machines (both for my MWE and the real data) .

**Comment by Datseris** [comment]
Alright, whoever hasn't yet achieved the 4 Hacktoberfest PRs, feel free to do a PR that changes this!
