### ISSUE TITLE
Support for BIDS Style Datasets

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaDynamics/DrWatson.jl#206]
Hello DrWatson Team.

Would it be possible for DrWatson to handle Brain Image Data Structured (BIDS) datasets? The dataset structure generally looks like this:

![image](https://user-images.githubusercontent.com/29561456/97112800-b0c07e00-16bc-11eb-8062-3867935bd11e.png)

> Source: https://bids.neuroimaging.io/

I was curious if there was a way in DrWatson to handle this natively. I found [BIDSTools.jl](https://github.com/TRIImaging/BIDSTools.jl) which supports this sort of parsing:

```julia
julia> layout = Layout("/path/to/bids/root/")
Layout:
    root = /path/to/bids/root/
    total subject = 125
    total session = 137
    total files = 2945

julia> for sub in layout.subjects
           for ses in sub.sessions
               for file in ses.files
                   # do something
               end
           end
       end
```

And was curious if I could replicate the same sort of functionality with DrWatson via `datadir()` and such. More just looking to see if DrWatson has a generic solution I could use rather than using this separate package.

I look forward to your thoughts and suggestions about this. Thanks!

**Comment by Datseris** [comment]
Hi there,

the only think I can think of is doing `Layout(datadir("path"))`.

>  More just looking to see if DrWatson has a generic solution I could use rather than using this separate package.

I think this is not a bad idea. If a package offers a functionality that is useful for you, you should use it :) 

However, I can also say that given that you have a standardized format, you can write your own function that crawls through this layout.

**Comment by TheCedarPrince** [comment]
Ah gotcha. The `Layout(datadir())` idea is great. Very true. I think I shall just use that package to handle the dataset instead of relying on DrWatson for everything. Thanks @Datseris - closing the issue. :smile:
