### ISSUE TITLE
@onlyif can't handle vector values

### ISSUE THREAD

**Issue by JonasIsensee** [JuliaDynamics/DrWatson.jl#209]
On the latest release and julia `v1.5.2`:

```julia
julia> using DrWatson
julia> dict_list(Dict(
           :a => [1,2,3],
           :b => [@onlyif(:a==1, 10), @onlyif(:a==2, [20]), @onlyif(:a==3, [30,30])]))
7-element Array{Dict{Symbol,V} where V,1}:
 Dict(:a => 1,:b => 10)
 Dict{Symbol,Any}(:a => 1,:b => DrWatson.DependentParameter{Int64}[DrWatson.DependentParameter{Int64}(20, var"#14#17"())])
 Dict{Symbol,Any}(:a => 2,:b => DrWatson.DependentParameter{Int64}[DrWatson.DependentParameter{Int64}(20, var"#14#17"())])
 Dict{Symbol,Any}(:a => 3,:b => DrWatson.DependentParameter{Int64}[DrWatson.DependentParameter{Int64}(20, var"#14#17"())])
 Dict{Symbol,Any}(:a => 1,:b => DrWatson.DependentParameter{Int64}[DrWatson.DependentParameter{Int64}(30, var"#15#18"()), DrWatson.DependentParameter{Int64}(30, var"#15#18"())])
 Dict{Symbol,Any}(:a => 2,:b => DrWatson.DependentParameter{Int64}[DrWatson.DependentParameter{Int64}(30, var"#15#18"()), DrWatson.DependentParameter{Int64}(30, var"#15#18"())])
 Dict{Symbol,Any}(:a => 3,:b => DrWatson.DependentParameter{Int64}[DrWatson.DependentParameter{Int64}(30, var"#15#18"()), DrWatson.DependentParameter{Int64}(30, var"#15#18"())])
```

**Comment by JonasIsensee** [comment]
So, this actually isn't entirely trivial.
This could either give
```
Dict(:a => 1,:b => 10)
Dict(:a => 1,:b => 10)
```

**Comment by sebastianpech** [comment]
Hm. Not sure that's a bug, maybe rather a design decision.
@JonasIsensee would you assume that if `@onlyif` is used inside a vector it should not expand its argument?
So we would need context-specific behavior, not sure that's possible with the current design though ...

**Comment by JonasIsensee** [comment]
Well, I'm not sure what behaviour would be best but I still think this is a bug because I cannot see any reason
as to why the resulting list of dicts should contain `DrWatson.DependentParameter`s.
That is almost certainly not what the user wants.

I don't know the internals in detail but I can see that the recursive expansion of dependent vectors might be hard to do.
But the first of my suggested outputs should be possible, no?

**Comment by sebastianpech** [comment]
Changing this isn't too difficult. The broadcasting is done here in line 151.
https://github.com/JuliaDynamics/DrWatson.jl/blob/becefb8718c8edb4439d1bc3ce2db2161e696037/src/dict_list.jl#L149-L154
The thing is, the macro can't know if it's inside a vector or not.

**Comment by Datseris** [comment]
> I'm not sure what behaviour would be best but I still think this is a bug because I cannot see any reason
as to why the resulting list of dicts should contain DrWatson.DependentParameters.

I would agree with this statement, but my macro-knowledge is so low, I cannot contribute more to the discussion here :P

**Comment by sebastianpech** [comment]
>Well, I'm not sure what behaviour would be best but I still think this is a bug because I cannot see any reason
as to why the resulting list of dicts should contain DrWatson.DependentParameters.

Oh ok. So it's actually two things you think are wrong here?
1. Too much or unnecessary output and
2. unexpected expansion of the arguments

**Comment by sebastianpech** [comment]
Oh. I'm not sure why it shows the DependentParameter stuff at all. That shouldn't be there.
Hmm maybe you guys are right and it is a bug. I have to look into that.
I just tried your case with Tuple instead of Vector and this gives the expected result, without the DependenParameters:
```
dict_list(Dict(
                  :a => [1,2,3],
                  :b => [@onlyif(:a==1, 10), @onlyif(:a==2, (20,)), @onlyif(:a==3, (30,30))]))
3-element Array{Dict{Symbol,V} where V,1}:
 Dict{Symbol,Any}(:a => 2,:b => (20,))
 Dict{Symbol,Any}(:a => 3,:b => (30, 30))
 Dict(:a => 1,:b => 10)
```

**Comment by JonasIsensee** [comment]
>I just tried your case with Tuple instead of Vector and this gives the expected result, without the DependentParameters:

Yeah, that's what I've done in my code as well, for now.

Well, there is only one thing that is *wrong* and that is that there are `DependentParameters` in the output.
Everything else is debatable.
The problem is probably that the normal expansion returns a vector of vectors of `DependentParameters`
which in turn isn't seen by the algorithm that does the dependency resolution.


I could imagine sidestepping this problem by enhancing the macro to accept
```
   @onlyif(:a==1, 10, :a==2, (20,), :a==3, [30,40]) 
```
so that we don't have to put `@onlyif` into a vector in the first place
