### ISSUE TITLE
Savename for DataFrames?

### ISSUE THREAD

**Issue by maniamaster** [JuliaDynamics/DrWatson.jl#214]
Savename works great for saving raw simulation data, where each parameter configuration creates a single file.
However, how would you use it if you load that data with collect_results(), filter the dataframe and plot it?

I tried using savename on the filtered DataFrame, without success.

**Example:**

Let's say I have two parameters x and y

x = [1,2]
y = [0.1,0.2]

So, using dict_lists I end up with four files. I load them with d = collect_results() and filter the dataframe d via

df = d[d.y == 0.1,:] .

When plotting, is it possible to generate the proper savename "y=0.1.pdf"? I had hoped one could convert the filtered dataframe into a dict with :y => 0.1, :x. => [1,2]. 

EDIT: Okay, It seems I've found a solution. 

savename(copy(df[1,:])) works for a dataframe df that has been filtered to only have one row. So I guess savename could be customized to have exactly this behaviour.

If this is obvious, this question can be deleted.

**Comment by Datseris** [comment]
I'm not sure whether `savename` should be implicitly copying anything. Why do you need the `copy` function there? what happens if you do simply `savename(df[1,:])` ? 

P.s.: In the future please do code formatting using the buttons GitHub provides when you are writing a message :)
