### ISSUE TITLE
Error: The following package names could not be resolved: DrWatson

### ISSUE THREAD

**Issue by rleyvasal** [JuliaDynamics/DrWatson.jl#216]
I am not able to install DrWatson on Julia PowerShell.

Running on:
Windows 10 Pro 64bit

![DrWatson_cannot_install](https://user-images.githubusercontent.com/61335136/99867657-198dff80-2b70-11eb-935f-307675fda3af.PNG)

**Comment by tamasgal** [comment]
Are you able to install any other package? It seems that you are using some local registry instead of the official one...

**Comment by rleyvasal** [comment]
I just found it was my installation problem -I had to do a clean
re-installation of Julia.

Please close the issue.

**Comment by tamasgal** [comment]
Glad to hear you could fix it.

Have fun 🙂
