### ISSUE TITLE
savename((;a=1e3),"bson") gives "a=1000.bson"

### ISSUE THREAD

**Issue by omerchiers** [JuliaDynamics/DrWatson.jl#220]
I think this is related to #163

Initially I made a  [discourse post](https://discourse.julialang.org/t/drwatson-jl-how-to-put-a-float-1e15-in-the-name-and-how-to-save-txt-files/49875?u=olivier_merchiers).

When I do 
`savename((;a=1e3),"bson")`

I get
`"a=1000.bson"`

While instead I would expect
`"a=1e3.bson"`

This is in v1.16.6.
adding ` ;scientific =2` doesn't change anything.

**Comment by Datseris** [comment]
Yeap, closing in favor of #163 (this is duplicate)
