### ISSUE TITLE
dict_list_count returns wrong number of elements with @onlyif

### ISSUE THREAD

**Issue by theogf** [JuliaDynamics/DrWatson.jl#223]
`dict_list_count` shows a different number than the resulting size of `dict_list`.

Here is a MWE : 

```julia
dict = Dict(
    :a => [1, 2, 3],
    :b => [1:9..., @onlyif(:a > 1, collect(10:10:99))..., @onlyif(:a > 2, collect(100:100:1000))...] # I did not find a nicer way to write this
)

length(dict_list(dict)) == 55
dict_list_count(dict) == 84
```

With julia 1.5 and DrWatson 1.16.6

**Comment by sebastianpech** [comment]
Maybe a dispatch problem, will check that later. As it's not possible to predict the count, I'm actually just computing it like you did.

**Comment by theogf** [comment]
I should have said that this is in no way a critical bug for me. I just use `dict_list_count` for display purposes. I just wanted to report it :)
