### ISSUE TITLE
Submodules flag not working in older versions of git.

### ISSUE THREAD

**Issue by racinmat** [JuliaDynamics/DrWatson.jl#224]
**Describe the bug**
When using `git version 1.8.3.1`, `gitpatch` causes
```
fatal: Failed to parse --submodule option parameter: 'diff'
┌ Warning: `gitpatch` failed with error ProcessFailedException(Base.Process[Process(`git --git-dir=<my_path>/.git --work-tree=<my_path> diff --submodule=diff HEAD`, ProcessExited(128))]), returning `nothing` instead.
```

**Minimal Working Example**
```julia
using DrWatson
DrWatson.gitpatch()
```

**DrWatson.jl version**
DrWatson, version 1.16.5 and newer.
Caused by https://github.com/JuliaDynamics/DrWatson.jl/pull/212
Git version 1.8.3.1.
Works on 1.16.4.

Would it be possible to check for the git version and use newer version with submodules only when git itself supports it, so it wouldn't break when using older git?
Thanks.

**Comment by Datseris** [comment]
(comment: This difference patching functionality have been causing many problems since it was added, and I'm not sure how many people actually use it. I think we should consider making it off by default. I don't think it will be a breaking change (like what kind of user code would break...?)

**Comment by Datseris** [comment]
cc @sebastianpech from #212

**Comment by sebastianpech** [comment]
@Datseris 
> This difference patching functionality have been causing many problems since it was added

Which other problems besides the version incompatibility do you mean? I haven't had any problems yet and I'm heavily relying on this. Maybe there is an option without making this a toggleable feature.

**Comment by racinmat** [comment]
Maybe just make it default for newer versions of git, determined by `read(`git --version`, String)` and not use it for old versions?
But I'm not sure in which version of git the diff for submodules was exactly added.

**Comment by sebastianpech** [comment]
That would definitely work, but if there are some other issues we should fix them as well.

**Comment by Datseris** [comment]
I recall 2 bugs being reported+fixed about the patching functionality since it was merged and 1 more that I fixed without reporting after encountering it personally. However, I might remember wrong, please don't quote me. My point of thinking was "effort of supporting a feature versus people actually using it", because I was wrongly thinking it is not a often used feature, yet people encounter these bugs regardless of whether they care to use this feature or not.

But now that I see it is a used feature, we just have to fix the bug.

**Comment by racinmat** [comment]
In our team, we use patches quite a lot (not that much time to commit when you are rapidly experimenting :D ), but without submodules currently.
