### ISSUE TITLE
Relaxing type restrictions in saving functionality

### ISSUE THREAD

**Issue by JonasIsensee** [JuliaDynamics/DrWatson.jl#229]
Hi,

in my research I've come across problems with different file systems mounted on different machines.
To solve this I've implemented something like

```
mutable struct ClusterPath
    host::Cluster
    path::String
    localpath::String
    function ClusterPath(host, path)
        cp = new(host, path)
        if islocal(cp)
            cp.localpath = path
        else
            cp.localpath = joinpath(TMP, basename(path))
        end
        return cp
    end
end
```

where `ClusterPath` extends all the usual functionality of a path e.g. `joinpath`, `FileIO.load`, etc.
and copies the files to and from the given hosts as necessary.

Now, I'd really like to use this everywhere in my scripts but currently this is not compatible with e.g. `produce_or_load`
simply because of
```
function produce_or_load(path::String, c, f::Function;
```
an explicit requirement for `path` to be a `String`.
When I remove that locally it works just fine since the type is not required for dispatch.

What do you think? Would it be acceptable to remove/relax those type restrictions in DrWatson?

Would a more general consideration of paths be useful?
See e.g. 
https://github.com/rofinn/FilePathsBase.jl
https://github.com/rofinn/FilePaths.jl

**Comment by Datseris** [comment]
> Would it be acceptable to remove/relax those type restrictions in DrWatson?

I mean, you're one of the core devs, you should be able to decide on the spot :P 

For me totally fine of course. https://rofinn.github.io/FilePathsBase.jl doesn't work for me, broken link.

> Would a more general consideration of paths be useful?

Yes for sure, perhaps in many other parts of the library. How does your `ClusterPath` work with stuff like `projectdir`?

**Comment by JonasIsensee** [comment]
> I mean, you're one of the core devs, you should be able to decide on the spot :P
I know, but DrWatson is way beyond 1.0 and I value your opinion.

Sorry about the link. I edited it above.

> Yes for sure, perhaps in many other parts of the library. How does your ClusterPath work with stuff like projectdir and safesave?

Good question, that depends a bit on what operations these functions do. 
For me, `ClusterPath` is meant to represent file paths that are not necessarily accessible from my machine directly. So `projectdir` is not really meaningful here. `safesave` on the other hand could be useful. For that to work, I would need to extend
`splitdir`, `splitext`, `joinpath`, `isfile`, and `mv` which all seem reasonable for a custom `Path` interface.
However, my implementation of `ClusterPath` is rather customized to our local cluster architecture and it could be more like a real-world example, rather than functionality of DrWatson.

I think, for now it would be best to relax type constraints in relevant functions, where possible,
and maybe link the `FilePaths` packages in the docs. 
While attractive in principle, I cannot yet come up with cases where an explicit handling of `Path` vs `String` will
be useful.

I'll prepare a PR soonish.

**Comment by Datseris** [comment]
Ah, I now remembered PR #227 which added constraint to the variable of `produce_or_load`. We just have to be a bit more careful here to avoid conflicts. Probably dispatch between `::Function` and `::Any` is enough, using the `::Function` to identify which argument is `f`. If this is not enough, then we can drop #227. Because #227 is 2-liner convenience, while the issue discribed here is a real issue.

**Comment by JonasIsensee** [comment]
Dispatch between `::Function` and `::Any` seem to be enough. It works for my application and tests pass on #230 .
