### ISSUE TITLE
Switch all doc to use JLD2.jl instead of BSON.jl

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DrWatson.jl#231]
Using BSON.jl in our docs leads newcomers of Julia to using BSON instead of JLD2, which I think is really not a good idea... We should really change it.

p.s.: I'm really surprised that new users come to DrWatson first before even checking out a package to save files :D

**Comment by BoZenKhaa** [comment]
To add a beginner's user story: I found out about DrWatson shortly after I have researched packages for saving files and was overwhelmed with the number of options and wasn't sure what to pick. After seeing that DrWatson implicitly recommends BSON.jl, I started using that. Then I started getting issues from using BSON, so I went looking again...
