### ISSUE TITLE
Would possible to use engineering notation for floating-point numbers?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaDynamics/DrWatson.jl#232]
**Is your feature request related to a problem? Please describe.**
Large or small numbers make for bad simulation names. This might help.

**Describe the solution you'd like**
Example: `sim_E=2.1e11`.

**Describe alternatives you've considered**

**Comment by sebastianpech** [comment]
I'm closing this in favor of the discussion in the referenced issue.
