### ISSUE TITLE
savename large integers with scientific string

### ISSUE THREAD

**Issue by roiholtzman** [JuliaDynamics/DrWatson.jl#235]
I am running simulations which often have large integer number specifying the number of realisations I am running. These numbers are typically 1e6.
Using `savename` gives the string `N=1000000`, however I would prefer that it would write `N=1e6`. I tried to look in the documentation, but I didn't find how to manipulate this properly. Specifically I tried to use `val_to_string` but it didn't work.

If there is an easy way to do this, please let me know.

**Comment by Datseris** [comment]
You need to convert to float. Julia does not represent integer numbers in scientific notation:
```julia
julia> using DrWatson

julia> a = 1e6
1.0e6

julia> b = Int(a)
1000000

julia> @savename a b
"a=1e6_b=1000000"
```

(also, be sure to update DrWatson to v2.0)

**Comment by Datseris** [comment]
We can't leave this open as a Feature Request, because it breaks `parse_savename`: the number `1e6` will always be parsed as a `Float64` by Julia, while the number `1000000` will always be parsed as an Integer. Thus, we cannot provide "automatic conversion" of large integers to scientific notation.

**Comment by Datseris** [comment]
Further comment: in DrWatson 2.0 we decided to treat Ints and Floats as Julia does: they are different things and no mixing of each other is done automatically or internally.

**Comment by roiholtzman** [comment]
> You need to convert to float. Julia does not represent integer numbers in scientific notation:
> 
> ```julia
> julia> using DrWatson
> 
> julia> a = 1e6
> 1.0e6
> 
> julia> b = Int(a)
> 1000000
> 
> julia> @savename a b
> "a=1e6_b=1000000"
> ```
> 
> (also, be sure to update DrWatson to v2.0)

Thanks. But this parameter should be an integer for the Julia code, therefore I cannot simply convert it. Is there a way to convert it only for the purpose of `savename`?

**Comment by Datseris** [comment]
Can you try calling `savename` with the keywrod argument `val_to_string  = x -> string(float(x))` and tell me how it goes?

**Comment by roiholtzman** [comment]
yes. 
it converts everything to floats:
```
savename(dicts[1], val_to_string = x -> string(float(x))) 

"L=512.0_Nreal=1.0e6_Nsteps=1.0e6_gamma=1.25_r0=10.0_r_jump=1.0_ρbar=0.1"
```

To get only the large numbers are converted to floats, I tweaked it like this:
```
function pretty_int(x)
    if x > 10000
        return string(float(x))
    else
        return string(x)
    end
end

savename(dicts[1], val_to_string = x -> pretty_int(x))

"L=512_Nreal=1.0e6_Nsteps=1.0e6_gamma=1.25_r0=10_r_jump=1_ρbar=0.1"
```
