### ISSUE TITLE
Savename function to modify a key name (to replace unicode characters to ASCII)

### ISSUE THREAD

**Issue by mbruna** [JuliaDynamics/DrWatson.jl#237]
**Is your feature request related to a problem? Please describe.**
I am using the savename function to save data files and figures with the string of parameters that identify a given simulation. I have some parameters named with greek letters, meaning that for example a figure is named:
ic1=left_ic2=right_pot1=none_pot2=quadratic_δ=0.7.eps
The problem is then that I cannot include this figure in a latex document as it cannot cope with the δ. At the moment I'm manually replacing it with a d.

**Describe the solution you'd like**
I would be ideal to have an option in savename so that I could ask to replace the key δ by d (in a similar way that one can now include some keys to be ignored). That is, something like this:
savefig(p, plotsdir("TimePlots", savename(ParamDict, "eps"; sigdigits = 3, ignores = ["k","α","dt"], replaces = [("δ","d")])))

**Describe alternatives you've considered**
Otherwise, I could continue using the savename as it is, and modify all the eps file names afterwards (but I don't know how to do this in an automated way).

**Comment by Datseris** [comment]
I don't think this is in the realm of DrWatson, nor that it is worth it to complicate `savename` further for it.

You can just do `name = replace(savename(your_dictt), "δ" => "d")`. 

An automatic way to find all unicode is not part of what DrWatson should be doing.

**Comment by Datseris** [comment]
See also https://docs.julialang.org/en/v1/manual/strings/

**Comment by mbruna** [comment]
Thanks, I agree this is much simpler.
