### ISSUE TITLE
savename for scientific notation does not work on windows

### ISSUE THREAD

**Issue by omerchiers** [JuliaDynamics/DrWatson.jl#238]
Hello,

We are on DrWatson 2.0.1: 
```
(Our_project) pkg> st
Status `C:\Users\Our_project\Project.toml`
  [634d3b9d] DrWatson v2.0.1
```

And
```
julia> versioninfo()
Julia Version 1.5.4
Commit 69fcb5745b (2021-03-11 19:13 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = "C:\Users\cbourgain\AppData\Local\Programs\Microsoft VS Code\Code.exe"
  JULIA_NUM_THREADS =
```
however, savename does not output the desired result:

```
a = 1e-6
b = 1000
@savename a b
"a=0.0_b=1000"
```
instead of 
`"a=1e-6_b=1000"`

Thanks in advance
Olivier

**Comment by sebastianpech** [comment]
Hi. `savename` does automatic rounding of floats to three significant digits. You can change that by passing `sigdigits`.
```julia
julia> savename((@dict a b),sigdigits=10)
"a=1e-6_b=1000"
```

**Comment by omerchiers** [comment]
Thanks a lot!
Sorry that I missed that.
Is this documented somewhere? Because in [this comment](https://github.com/JuliaDynamics/DrWatson.jl/issues/235#issuecomment-797399691) the sigdigits kwarg does not appear.
Thanks again!

**Comment by sebastianpech** [comment]
Sure. You can have a look at it online at https://juliadynamics.github.io/DrWatson.jl/dev/name/#DrWatson.savename or just type `?savename` into the REPL. `sigdigits` is described under "Standard keywords".
