### ISSUE TITLE
Module in src is not loaded when importing

### ISSUE THREAD

**Issue by omerchiers** [JuliaDynamics/DrWatson.jl#248]
Hello,

I started this discussion in another issue (https://github.com/JuliaDynamics/DrWatson.jl/issues/183#issuecomment-831126646), but I was advised to open an new one.

In https://juliadynamics.github.io/DrWatson.jl/dev/real_world/#Making-your-project-a-usable-module-1
one can find the following instructions:
> If one defines inside the src folder a file AlbedoProperties.jl and in that file define a module AlbedoProperties (notice that these names must match exactly the project name), then upon doing using AlbedoProperties Julia will in fact just bring this module into scope.

Following exactly those instructions, julia tells me:

```
julia> using Detectivity
ERROR: ArgumentError: Package Detectivity not found in current path:
- Run `import Pkg; Pkg.add("Detectivity")` to install the Detectivity package.
```
This module lives in a DrWatson project that is properly activated.
I don't really understand the instructions as they seem to contradict julia's [code loading mechanism](https://docs.julialang.org/en/v1/manual/code-loading/) which requires either "include("MyModule.jl")" and "using .MyModule", or create a package with a Project.toml and add to the project, or modifying LOAD_PATH.
Following the instructions from the error message above, means my module should be project with a Project.toml.
I can do that of course, but this is not really what is written in the [instructions](https://github.com/JuliaDynamics/DrWatson.jl/issues/183#issuecomment-831126646). Or is it written somewhere else?

This is my setup
```
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```
My editor is VSCode

Thanks in advance,
Olivier

**Comment by Datseris** [comment]
can you paste your full project folder structure please?

**Comment by omerchiers** [comment]
Like this?
I omitted the output files to make it lighter

```
.
├── data
│   ├── exp_pro
│   ├── exp_raw
│   └── sims
├── Manifest.toml
├── notebooks
├── papers
│   └── presentation
├── plots
│   ├── absorption_efficiency
│   └── batch_calculation
├── Project.toml
├── README.md
├── _research
├── scripts
│   ├── AbsorptionEfficiency.jl
│   ├── AnalyticalModelAbsorber.jl
│   ├── data_comparison.jl
│   ├── detectivity.jl
│   ├── intro.jl
│   ├── near_field.jl
│   └── utils.jl
└── src
    └── Detectivity.jl
```

**Comment by Datseris** [comment]
What is the `.`? All of this should be inside a folder called `Detectivity`, and the project name must also be `Detectivity`.

**Comment by omerchiers** [comment]
OMG, I'm so sorry. I get it now. 
That works indeed.
I thought this part of the manual was about how to access other modules defined in src. I misread.

Sorry again for the noise and thanks a lot for your help
Olivier

**Comment by Datseris** [comment]
So is the documentation clear or not in the end? If not, can you do a PR?

**Comment by omerchiers** [comment]
I think the documentation is perfectly fine. 
Thanks again for your time
