### ISSUE TITLE
Track notebooks by clearing cell outputs with git hooks

### ISSUE THREAD

**Issue by thompsonmj** [JuliaDynamics/DrWatson.jl#256]
**Is your feature request related to a problem? Please describe.**
Notebooks can be an important part of a project that can change over time, but git does not track them well when cell outputs are present. Including `notebooks/` in the `.gitignore` file is a reasonable first approach, but it would be helpful to have notebooks tracked with automatically-cleared outputs prior to commits.

**Describe the solution you'd like**
Initializing a project with a `.githooks/` directory and  `git config --local core.hooksPath .githooks` , where scripts to automatically clear cell outputs prior to commits are kept in `.githooks/` and versioned with git, would help enable and manage notebook version control.

**Describe alternatives you've considered**
n/a

**Comment by Datseris** [comment]
I think it is even more helpful to note use the jupyter notebook format at all. I use Literate.jl and only convert to a notebook just before I have to present. Others use Pluto.jl. If the request is to automatically clear output, perhaps going for an alternative that already does it is the best idea.

**Comment by tamasgal** [comment]
...also some users would like to store the output for static demos.

The idea of git hooks is nice but I would not alter the data without explicitly asking the user. I'd rather prefer scripts which warn the users about things like "don't commit a 100MB HDF5 file", etc `;)`

**Comment by Datseris** [comment]
@thompsonmj I think this won't be going into the DrWatson repo due to the automatic data altering nature. However, you are welcome to write a tutorial about this in our documentation, under the page "real world examples". There you can illustrate how a user can manually "clear output" from Jupyter notebooks, which will definitely help some users!

**Comment by Datseris** [comment]
*(actually, I'll keep this open as a reminder to add the documentation)*
