### ISSUE TITLE
quickactivate only works if DrWatson is installed globally

### ISSUE THREAD

**Issue by fonsp** [JuliaDynamics/DrWatson.jl#261]
`quickactivate` is a useful function/macro, but it is only available when DrWatson is imported. But how can you import DrWatson before activating your project environment?

Currently, the docs suggest this:
```julia
using DrWatson # YES
quickactivate(@__DIR__)
using Package1, Package2
# do stuff
```

which will work if you have DrWatson installed **globally**. But when you send your work to someone else, it won't work, even though you took care to include a `Project.toml`/`Manifest.toml` in your repository. It can lead to the false assumption that your repository will run on another computer.

**Comment by Datseris** [comment]
Yeap, that's the "caveat" of `quickactivate`. We have a large warning in its docstring if you have a look here: https://juliadynamics.github.io/DrWatson.jl/dev/project/#DrWatson.quickactivate 

Unfortunately, I can't imagine a workaround. Feel free to suggest something.

**Comment by Datseris** [comment]
Perhaps something we can do is add this notice in the automatically generated README file that DrWatson creates on `initialize_project`. It already has reproducibility steps written out, but I guess it's missing that if `quickactivate` is used (which typically every DrWatson project does this), then you need DrWatson in global environment.

Thoughts?

**Comment by fonsp** [comment]
As long as the reproducibility steps work independently of your global package environment, then the reproducibility issue is solved!

But my personal preference would be to either make a PR to add this directly to Pkg, or to find a way to make it simple for users to just write `Pkg.activate(joinpath(@__DIR__, "..", ".."))` with the appropriate number of `".."`.

**Comment by Datseris** [comment]
> to find a way to make it simple for users to just write Pkg.activate(joinpath(@__DIR__, "..", "..")) with the appropriate number of "..".

Well, that's what `quickactivate` does.

I'll start with improving the documentation around this, and we'll see if this ever goes into Pkg.

**Comment by fonsp** [comment]
Sorry, I meant: advertise that users should literally write `Pkg.activate(joinpath(@__DIR__, "..", ".."))` since that does not have this issue, and perhaps find a way for them to easily find the number of `".."` to use. For example, you could have a command:

```julia
julia> @getquickactivate
🕵️: Detected an environment!
Use this command: Pkg.activate(joinpath(@__DIR__, "..", ".."))
```

**Comment by Datseris** [comment]
Feel free to open an issue at Pkg, you are probably much more likely to convince people to let this in.

Regarding your suggestion: I think installing DrWatson at the global environment is a much simpler process than (a) manually finding the relative path using some function and (b) doing this for every single script file individually and (c) re-writing this path every time you move your script to a subfolder for better organization.

**Comment by Datseris** [comment]
One of the neat things of `quickactivate` is when it can do:

```julia
@quickactivate :ProjectName
```

see e.g. https://juliadynamics.github.io/DrWatson.jl/dev/real_world/#Making-your-project-a-usable-module-1  

Not sure how much this fits into Pkg, but you can try to convince the Pkg authors!

**Comment by fonsp** [comment]
Thanks for changing the docs! I opened the issue because `quickactivate` will not work in future versions of Pluto (https://github.com/fonsp/Pluto.jl/wiki/%F0%9F%8E%81-Package-management), because of this loading order problem. Maybe you can add this to the warning in the docs?

**Comment by Datseris** [comment]
I do not understand. If I read correctly your docs, when someone does `using Whatever` it is installed automatically? So, given that to use `quickactivate` you need to start your script with `using DrWatson`, shouldn't it be installed automatically?

**Comment by fonsp** [comment]
It doesn't work because you can either use Pluto's built-in package manager or completely disable it. For quickactivate to work, it would have to do both

**Comment by Datseris** [comment]
I'm a bit confused about your approach "the environment is tied to the notebook". It seems incompatible with scientific projects that have more than one script...? Or at least one script and at least one source file. How does it work there? For each notebook the user needs to start a new environment, no? So even if two scripts are path of the same scientific project, they would each get their own environment?

And what happens when source files are loaded? I have defined a bunch of functions in `src/processing.jl`, and the file also includes a bunch of `using` statements. When I do `include("src/processing.jl")`, are these packages automatically added to the Pluto environment?

**Comment by Datseris** [comment]
> Maybe we can chat on slack?

Sure go ahead! I'm only concerned of losing useful exchanges after a week :D

**Comment by fonsp** [comment]
@Datseris and I talked on zulip and the result is:
1. https://github.com/JuliaLang/Pkg.jl/issues/2640
2. If it does not get accepted/released soon, I will think about an easier way to make this use case work for Pluto users, i.e. without having to manually write `Pkg.activate(joinpath(@__DIR__, "..", ".."))`
