### ISSUE TITLE
[FR] function `isdirty(path = projectdir())`.

### ISSUE THREAD

**Issue by dingraha** [JuliaDynamics/DrWatson.jl#263]
Often when using DrWatson I'll forget to commit before running something with `produce_or_load`, leading to a dirty git commit/patch. I'd rather have DrWatson refuse to run the function and give me a chance to commit everything and try again. So how about adding a keyword argument like `allow_dirty`, defaulting to `true`, to `produce_or_load` that would throw an error when the repository isn't clean if `allow_dirty==false`?

DrWatson is awesome. Thanks for this package!

**Comment by Datseris** [comment]
Thanks!

I think a better alternative would be to expose a function `isdirty(gitpath)` that returns `true` if it is dirty, and you can decide what you want to do with it. E.g. preface your `produce_or_load` calls with `isdirty(path) && error()`. I don't think that `produce_or_load` should have much to do with `git`, its git-related arguments are just some paths propagated to other functions.

**Comment by dingraha** [comment]
> I think a better alternative would be to expose a function `isdirty(gitpath)` that returns `true` if it is dirty, and you can decide what you want to do with it.

Even better!

**Comment by dingraha** [comment]
Thanks for merging this!
