### ISSUE TITLE
Increase verbosity of `collect_results`

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DrWatson.jl#27]
Hi Jonas, 

I am writing the final "real world example" which uses your `collect_results`. However both arguments black_list and special_list  seem to fail. There is also no warning/error thrown so I don't get why.

I think I am using them as the documentation suggests. Can you have a look in https://juliadynamics.github.io/DrWatson.jl/dev/real_world/#Listing-completed-runs-1 and tell me what is wrong? The code is runnable you can run it locally by running the `make.jl` file (and you will have all the results almost instantly).

**Comment by JonasIsensee** [comment]
Not a bug.
Your second run of `collect_results` with `special_list` finds no new files thus not adding anyting.
`collect_results` saves the resulting DataFrame by default.

 If you find this tricky you may want to add more verbose `@info`s like 
`Loading existing DataFrame`
`$N new entries were added`

The following works for me:
```
using Statistics
special_list = [:avrg_error => data -> mean(data["error"])]
res = collect_results(
      datadir()*"results",
      black_list = black_list,
      special_list = special_list,
      filename = ""
)
```

**Comment by Datseris** [comment]
Okay I'll add this info line. We should consider a `force` option as well, that will always process all files even if they exist in the path column.

**Comment by Datseris** [comment]
(by the way I also understand why `black_list` was failing locally for me; I have had already processed all files once in a previous doc build)
