### ISSUE TITLE
YouKeepUsingThatWord...

### ISSUE THREAD

**Issue by azraq27** [JuliaDynamics/DrWatson.jl#272]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by azraq27** [comment]
Hi,

I apologize profusely for my ignorence....

I've recently discovered DrWatson and found it to be _amazing!_ ... but... occasionally.... I've shared code that refers to multiple Pkg's (perhaps... _strange_ Pkg's...) where the recipient is not aware. Too much!! Oi!!! The Pkg's! It has overwhelmed them! The academic horror!?!?....

Is there any way – Julia-ic-ily – to _induce_ Pkg "addition" by `activating` a project?

As in, is there any way to programmatically set up a way to set up a way to run my experiment... or, am I stuck with leaving them a set of instructions of what Pkg's to install, etc!

Appreciate the work so far! Happy to hear any input.

-Bill

**Comment by Datseris** [comment]
Hi, I genuinely do not understand what you are talking about. Please rephrase your question in a simpler manner. What do you mean "multiple `Pkg`"? What do you mean  "is there any way to programmatically set up a way to set up a way to run my experiment... "? I don't even know what "experiment" means in this context.

**Comment by azraq27** [comment]
Sorry again, I think my lack of specificity is driven by my ignorance of how the new package system works.

I tried packaging up my experiment’s ‘DrWatson’ directory and sending it to a computer with a fresh Julia install (fresh + ‘DrWatson’). When I tried to run the scripts, it complained about certain packages (e.g., ‘JSON’) not being installed on the new machine. I had to manually add them to get it to work (e.g., ‘Pkg.add(“JSON”)’). When I say “strange” packages, I mean some of my packages aren’t easily available either, like ones that I manually added from a git repository that’s not listed in the main Pkg repo.

Does that make more sense? Sorry again for the ignorance.

**Comment by Datseris** [comment]
Did you follow the guidelines on reproducibility from DrWatson's documentation? Specifically here: https://juliadynamics.github.io/DrWatson.jl/dev//project/#Reproducibility-1 ?

I'm guessing you're missing the crucial `instantiate` step:

```
julia> cd("path/to/project")
pkg> activate .
pkg> instantiate
```

which installs all dependencies of the project.

**Comment by azraq27** [comment]
Yes! Thank you. I didn't read that close enough, and wasn't familiar with what `instantiate` did.
