### ISSUE TITLE
Its far from clear how findproject works

### ISSUE THREAD

**Issue by Masacroso** [JuliaDynamics/DrWatson.jl#275]
Hi. Im not sure if this is the correct way to say this but it is not clear in the documentation how `findproject` works. The only information about this is that it is something like

`findproject(path = pwd()) -> project_path`

However its not clear what exactly is `path`, neither `pwd()` nor `project_path`. After some tries I see that `path` is a string but it doesn't need to be quoted, and `pwd()` seems to be some kind of generic function of search, however it just seems to search in the $HOME folder. I guess that `project_path` is also a non-quoted string (however its unclear what is it use as it is supposed that you are searching a project path, so in first place you dont know what is this such path).

As you see the documentation is not very clear, it would be very helpful to understand it behavior to add two uses of this command, searching in different locations.

**Comment by Datseris** [comment]
The documentation string of `findproject` says:

![image](https://user-images.githubusercontent.com/19669089/128347573-aa21a4bd-09ed-457e-958e-2e1a5db77496.png)

So I disagree with you, as I can't imagine how one could make this statement more clear. Saying this is "far from clear" is too much of an exaggeration. `pwd()` is a Julia function that returns current working directory as a string, which you can see easily by typing `?` and then the function name:

![image](https://user-images.githubusercontent.com/19669089/128347890-bfaa0423-8b0f-4a82-94c4-b50226351e91.png)

**Comment by Datseris** [comment]
I guess we could change the signature in the docstring to `findproject(path::String = pwd())` , but I'm not sure how this would help more?

**Comment by Datseris** [comment]
Notice that a standard user has no reason to use `findpath` directly. They would instead use things like `projectdir` and `quickactivate`.

**Comment by Masacroso** [comment]
> Hi, have you seen the documentation string of the function? Because the question "what is `path`" cannot be answered by us. `path` is an input argument, so you decide what it is.
> 
> The documentation string of `findproject` says:
> 
> ![image](https://user-images.githubusercontent.com/19669089/128347573-aa21a4bd-09ed-457e-958e-2e1a5db77496.png)
> 
> So I disagree with you, as I can't imagine how one could make this statement more clear. Saying this is "far from clear" is too much of an exaggeration. `pwd()` is a Julia function that returns current working directory as a string, which you can see easily by typing `?` and then the function name:
> 
> ![image](https://user-images.githubusercontent.com/19669089/128347890-bfaa0423-8b0f-4a82-94c4-b50226351e91.png)

Seriously, this is not clear at all. I dont have any problem with other documentation of many packages, but this is really obscure. By example, if I want to search a project named `john` in `/media/`, what I must type? I tried `findproject(john)` or `findproject( "john")` or `findproject(john = pwd())` and other variants but it throw an error every time saying that `john`its an undefined variable.

**Comment by Datseris** [comment]
But this is not what the function does. It doesn't find a project of a given name. It finds a _potential project file_ that exists in the given `path`, or the parent folders of the given `path`. That's exactly what the documentation string says. Whether this project is named "john" or not, you can check with other means, i.e. with what the `projectname` function returns once you activate that project.

To find the project file in the path `"/media"` then you call the function `findproject("/media")` as one would expect from the documentation string. Notice that `"/media` is a path defined w.r.t current working directory `pwd()`. You need to give a global path if you don't want paths relative to the `pwd()`.

> other variants but it throw an error every time saying that `john` its an undefined variable.

This "problem" has nothing to do with DrWatson and it would be to your benefit to have a look at one of the Julia tutorials and/or online documentation.

> `findproject(john = pwd()) -> /media/ `

This syntax doesn't even make sense.
