### ISSUE TITLE
Support for OrderedDicts

### ISSUE THREAD

**Issue by rs7q5** [JuliaDynamics/DrWatson.jl#278]
I have been utilizing OrderedDicts more frequently and have been limited to some of the convenience functions or other things because the functions (e.g. tag! or dict_list) require the input to explicitly be a :Dict{K,T}.  

Since OrderedDicts are the same things as regular Dicts I don't think it should break anything major in the existing code and I just would like to be able to use many of the convenience functions that already exist without having to write a function that basically already exists for a dictionary. 

I think the feature is a simple solution of allowing tag! or similar functions that define the input to be a Dict to also allow OrderedDict. Not sure if that is just an additional method or what.

**Comment by sebastianpech** [comment]
Pretty sure they are subtyping `AbstractDict{K,V}`. So one just needs to replace all the `Dict` types.

**Comment by Datseris** [comment]
A pull request here would be highly appreciated!

**Comment by rs7q5** [comment]
@sebastianpech  I thought it was something simple like that, but I'm not fantastic with types so wasn't sure.  Should it just replace it with AbstractDict instead of Dict or OrderedDict?

**Comment by Datseris** [comment]
yes, but this replacement needs to happen in the source code of `DrWatson`, not on your end (i.e. not when you use DrWatson as a user). That's why you need to open a pull request to fix it. E.g. if you see a function definition `tag!(d::Dict, ...)` you simply have to change it to `tag!(d::AbstractDict, ...)`.

**Comment by rs7q5** [comment]
I'll work on that. I looked at it and think I have it fixed such that it will work, but for whatever reason my dev version of the package is pinning back to 2.2.0. I'm sure I can figure out a workaround for this though. A quick check with dict_list and tag! looks like it does work, but I haven't check all of the functions that it could maybe use.

As a side question, when I submit the pull request do I need to update version or anything particularly special? I don't have too much experience on the correct way of going about updating bugs, etc. so it may take me a bit to get it to pass everything it needs to.

**Comment by Datseris** [comment]
you should also update the version number in `Project.toml` by incrementing the third number of the version by one. For the dev version, I can't help much, this depends on how you manage git. (i haven't understood the problem either)
