### ISSUE TITLE
Recollection option for collect_results

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DrWatson.jl#28]
After a bit of usage of `collect_results` it seems like an option to "recollect" is useful.

By that I mean that by giving a keyword argument e.g. `recollect = true` all _existing_ data should be re-collected instead of being skipped.

I believe that this functionality should _not_ delete the saved dataframe and just start over. The reason for that is some old results still saved in the dataframe may not exist in the data folders any more. Then it would be irreversible to remove them. The best approach would be to just "replace" existing files if they still exist.

@JonasIsensee do you have any idea how this can be done? If some please give some help here. (Or if you can even implement this then you're the boss!)

**Comment by JonasIsensee** [comment]
instead (or additionally) to another argument we could consider exporting an _inplace_ and _outofplace_
version marked by `!`.
See my PR for an implementation for _backups_.
Feel free to integrate that into the relevant saving functions.

**Comment by Datseris** [comment]
This is a wonderful idea, i really like it!!!

I think it is clear that the out-of-place version will always produce a new dataframe with everything re-processed. (i.e. as if running the current version but first deleting the existing saved dataframe). We can also implement a `safe` keyword after #29. 

Now about the in place version, how do you envision it? From my perspective it always adds new result-files in place in the given directory by loading it (i.e. exactly what the current function does). However for the files already processed there are two approaches:

1. Re-process them.
2. Don't reprocess them (i.e. what the current function does).

Maybe we can keep both approaches through a keyword? i.e. `reprocess = false` by default?

**Comment by Datseris** [comment]
The `reprocess = true` keyword is actually equivalent with deleting the dataframe file and thus it is unnecessary.
