### ISSUE TITLE
`savename` documentation

### ISSUE THREAD

**Issue by fkastner** [JuliaDynamics/DrWatson.jl#284]
Hi,
I just noticed that the default values for the `savename` keywords that are given in the docs:
https://github.com/JuliaDynamics/DrWatson.jl/blob/953888eb7c8782ae1278601a0fc9d563ed7803c7/src/naming.jl#L37
do not match the real default values:
https://github.com/JuliaDynamics/DrWatson.jl/blob/953888eb7c8782ae1278601a0fc9d563ed7803c7/src/naming.jl#L87-L89

I would like to argue that the documented default values are the more sensible choice, because I just found out, that for `h = [1.0, 0.1, 0.01, 0.001, 0.0001, 1.0e-5, 1.0e-6]` we get 
```julia
julia> savename.(Dict.(:h.=>hs))
7-element Vector{String}:
 "h=1.0"
 "h=0.1"
 "h=0.01"
 "h=0.001"
 "h=0.0"
 "h=0.0"
 "h=0.0"
```
whereas with `sigdigits=3` we get
```julia
julia> savename.(Dict.(:h.=>hs), sigdigits=3)
7-element Vector{String}:
 "h=1.0"
 "h=0.1"
 "h=0.01"
 "h=0.001"
 "h=0.0001"
 "h=1e-5"
 "h=1e-6"
```
but I am aware that similar examples can be found for every possible default values for `digits`/`sigdigits`.
Should I open a PR to change the docstring or the default values?

**Comment by Datseris** [comment]
Hi, thanks a lot for noticing this. This is clearly a bug, the documented values (as you said) are more sensible and we simply forgot to update the source code. Please do open a PR!
