### ISSUE TITLE
question on @quickactivate with VS code

### ISSUE THREAD

**Issue by rs7q5** [JuliaDynamics/DrWatson.jl#291]
I am thinking about switching from Atom to VS Code and while doing so I had a question on the correct way of activating the environments. Currently the code technically runs and works by either just running `Julia: Execute active File in REPL` on one of my scripts that includes `using DrWatson` and `@quickactivate :ProjectName`. This works fine, but the Julia env: is not switched to `ProjectName` like it is in Atom (shown on the bottom status bars in the IDEs). This is likely a limitation of VS Code if anything, but I wanted to make sure there was no extra steps I needed to take to activate my project correctly. 

Not sure how related this is to #197 either.

**Comment by Datseris** [comment]
Not sure what's going on here because for me VSCode + `@quickactivate` work without a problem. Are you perhaps using `Ctrl+Enter` which doesn't evaluate in-line, but rather copy pastes to the REPL? This wont work because `@quickactivate` is a macro that needs to read the line it is evaluated at, and the repl has no such line.

Use Alt+Enter or Shift+Enter instead and get back to us.

**Comment by rs7q5** [comment]
The file works and runs, but down at the bottom I still have `Julia eng: v1.6`, now if you do `]` to enter the package manager you  do get `(ProjectName) pkg >` in the REPL, so I think I am in the right project, I just expected `Julia env:` to switch to `CombustionSimulations`. Or is that just reiterated on the `Run active Julia file (Combustion Simulations)`?

![image](https://user-images.githubusercontent.com/46969733/133945389-89e6a3f9-3a6e-495e-a85c-9ce66c9c3e80.png)

**Comment by Datseris** [comment]
If you see `(ProjectName) pkg >` in the REPL then all is fine and this message in the bottom of VSCode is a bug with vscode. Could you open an issue there instead?

**Comment by rs7q5** [comment]
That's what I was thinking, but I just wanted to be sure. Thanks! I'll go ahead and open an issue though.
