### ISSUE TITLE
Using gitdescribe inside savename

### ISSUE THREAD

**Issue by jonas-schulze** [JuliaDynamics/DrWatson.jl#306]
**Is your feature request related to a problem? Please describe.**
I have some packages checked out as submodules inside `src/` and I would like to include their version in `savename` as an alternative to the `savesafe` backup strategy:
```
vdep1 = gitdescribe(srcdir("Dep1.jl"))
vdep2 = gitdescribe(srcdir("Dep2.jl"))
config = (; vdep1, vdep2)
sname = savename(config)
```
If the submodules happen to be in a dirty state, `gitdescribe()` returns `..._isdirty`, which breaks `parse_savename` and friends.

**Describe the solution you'd like**
Change the default dirty repo suffix from `_dirty` to `-dirty`. This would also match `git describe --dirty`.

**Describe alternatives you've considered**
A non-breaking alternative would be to introduce a `dirty_suffix` kwargs for `gitdescribe` that defaults to the current `_dirty`.

**Comment by Datseris** [comment]
I count this as a bugfix because of missmatch with `git describe --dirty`, and as such it can be implemented in a patch increase!
