### ISSUE TITLE
Set seed

### ISSUE THREAD

**Issue by mvsoom** [JuliaDynamics/DrWatson.jl#308]
For reproducibility, perhaps this package can set the seed by default?

**Comment by Datseris** [comment]
The seed of what, and set it to what, and do it when? 

But I definitely do not see this as a wise option, too invasive.

**Comment by mvsoom** [comment]
The seed for random number generation. But I agree, a better way to do is manually in https://docs.juliahub.com/DrWatson/Vn5dT/1.14.4/real_world/#Making-your-project-a-usable-module-1.

**Comment by Datseris** [comment]
Notice that, at least in my opinion, using the global RNG is a bad idea. Not only it is bad for performance, but make things like seeding really non-transparent. A much better option is to initialize properly an RNG object with a given seed and explicitly use this object when you need random numbers.
```
rng = MersenneTwister(seed)
rand(rng)
```
