### ISSUE TITLE
Allow filtering file names with `collect_results`

### ISSUE THREAD

**Issue by junglegobs** [JuliaDynamics/DrWatson.jl#311]
I would like to be able to filter the results loaded which don't match a certain file name, since loading all the files in my folder of interest is quite time consuming.

Consider the following 3 files in a folder:

```
a=1_b=1.jld2
a=2_b=1.jld2
a=3_b=2.jld2
```

I would like to be able to write `collect_results(dir; exclude=[r"b=2"])` to only load files whose names match that Regex expression. Similarly you could perhaps think of doing `collect_results(dir; include=[r"b=1"])`.

Given the smart naming of files that DrWatson provides, this doesn't seem to outlandish no?

**Comment by Datseris** [comment]
Nope, it actually seems very sensible and rather straightforward to implement in code if you are willing to open a PR :)

**Comment by junglegobs** [comment]
Done!
