### ISSUE TITLE
Touch outputfile in `produce_or_load`

### ISSUE THREAD

**Issue by goerz** [JuliaDynamics/DrWatson.jl#317]
Loosely related to #315

Suppose someone has a `Makefile` or similar system to (re-)run a script if the `jdl2` output file the script produces has an older modification time than the script. However, the script uses `@produce_or_load`, so it won't actually do anything to the file (just "load" it). Consequently, the next time `make` (or whatever) runs, it will still see the same modification times and run the script again.

It might be nice if `@produce_or_load` had an option `touch=true/false` so that it touches (as in the [`touch`](https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.touch) function) the output `jdl2` file in the "load" case.

This behavior might be considered debatable. After all, if the script changes significantly, there's no guarantee that it would still produce the same output, and touching the output file would silently repress that. However, I'm thinking mostly of refactoring changes here that do not change the output. For more substantial changes, I'd manually deleted the `jdl2` file, causing `make` to recreate it.

**Comment by goerz** [comment]
If you think this is a terrible idea, it's also something I can solve at the level of the `Makefile`

**Comment by Datseris** [comment]
Adding a keyword `touch = false` which touches the file (if it exists) isn't really a big problem, I don't see why not adding it. Feel free to do a PR for this.
