### ISSUE TITLE
Best practice for simulations generating multiple output files

### ISSUE THREAD

**Issue by liuyxpp** [JuliaDynamics/DrWatson.jl#321]
I have gone through the whole doc of DrWatson, however, I cannot find any explanation on the scenario when a simulation emits multiple files. Or maybe I miss something. Can someone point me to the right place of the doc?

**Comment by sebastianpech** [comment]
It is not in the docs as this is not directly supported by DrWatson. This is the reason I wrote DrWatsonSim, which supports those cases by creating simulation directories linked to metadata entries. 

We are currently discussing adding parts or the whole functionality to DrWatson (#316). In the meantime, you can check out https://github.com/sebastianpech/DrWatsonSim.jl. The README contains a brief introduction and an example for a simulation which emits files.

**Comment by liuyxpp** [comment]
@sebastianpech Ahh Thanks! #316 is exactly what I want. But its title is misleading somehow...
