### ISSUE TITLE
collect_results undefined unless "using DataFrames"...?

### ISSUE THREAD

**Issue by elaird6** [JuliaDynamics/DrWatson.jl#325]
Several times I've manage to back myself into the infamous (?) "collect_results" failure and receive an UndefVarError due to the requirement to import/use DataFrames.  Could there be a better error message other than "UndefVarError" to gently remind users they need to import/Use DataFrames?  This is one of those quirks that is forgotten over time and then lots of hair pulling and teeth gnashing in trying to figure out why it's not working ...  especially when diving in and looking at stuff manually.

**Comment by Datseris** [comment]
Sorry, but it is (quite literally) impossible to change this error message. We don't control it.
