### ISSUE TITLE
`savename` abbreviates variables

### ISSUE THREAD

**Issue by junglegobs** [JuliaDynamics/DrWatson.jl#334]
My variable names are usually quite long so as to be easily read and understood, e.g. instead of `VOLL` I use `value_of_lost_load`. I have previously written a script which abbreviates such variables to avoid long file names - would this be an acceptable feature request?

**Comment by Datseris** [comment]
My guess is that you have some kind of dictionary of variable names to abbreviations:

```
c = Dict("value_of_lost_load" => "VOLL")
```
right?
so you would then replace the names using this dictionary?

I guess you could add this to the savename, as a feature, yeah.

**Comment by junglegobs** [comment]
No, it's just some sensible defaults for creating variable names i.e. remove underscores, keep only first letter after underscore and capitalise those letters.

**Comment by junglegobs** [comment]
Concretely I was thinking adding a keyword argument called `abbreviate` which would be `false` by default, if true it would do the above.

**Comment by Datseris** [comment]
Actually I now realized this breaks `parse_savename`, and given that it feels like a not so important piece of functionality, I'd rather leave it on the user end to do these transformations.

**Comment by junglegobs** [comment]
Fine with me if you close this then
