### ISSUE TITLE
Suppurt more types with savename

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaDynamics/DrWatson.jl#338]
`savename` is super cool, and I want to use it.

But my parameters include ranges, and instances of `DateTime`. So there are only 2 parameters included by the return-value of `savename`:
```
julia> params_small = (in1 = size(xtrain)[1:3], in2=10:12, out=10,
           possible_layers1 = 2:3, possible_layers2 = 1:2,
           time_budget = 5|>Minute, n_initial_NNs = 100
       )
(in1 = (28, 28, 1), in2 = 10:12, out = 10, possible_layers1 = 2:3, possible_layers2 = 1:2, time_budget = Minute(5), n_initial_NNs = 100)

julia> savename("random_search_results", params_small, "CSV")
"random_search_results_n_initial_NNs=100_out=10.CSV"
```

**Describe the solution you'd like**
I would love it for `savename` to be able to handle these types. A simple fallback would be to call `string` on unknown types:
```
julia> 5|>Minute |> string
"5 minutes"

julia> 10:12 |> string
"10:12"
```

**Comment by Datseris** [comment]
That's exactly what it does, it calls `string`:
```julia
julia> savename(x; allowedtypes = (Any,))
"a=2_b=1:4_c=5 minutes"
```

Unfortunately to allow this "from the get go" would mean altering the default converted types in `savename`, which is not only a breaking change, but one that is not worth a major version increment anyways. Notice that `TimeType` _is_ in the allowed types. But here you use a time _period_, not a `DateTime`.

**Comment by KronosTheLate** [comment]
All very fair. Thanks you for letting me know.
