### ISSUE TITLE
pkg>dev command not working as described in docs

### ISSUE THREAD

**Issue by jochenkrattenmacher** [JuliaDynamics/DrWatson.jl#339]
I am not sure whether this is intended, or I am missing something. 

I wanted to add my local git repo of "Agents.jl" to my project, as described [here](https://juliadynamics.github.io/DrWatson.jl/dev/project/#Default-Project-Setup-1). So I moved the Agents folder to the "src" folder of my DrWatson project.

Here is where I am, configuration-wise:
julia> DEPOT_PATH
3-element Vector{String}:
 "C:\\Users\\Jochen\\.julia"
 "C:\\Users\\Jochen\\AppData\\Local\\Programs\\Julia-1.7.2\\local\\share\\julia"
 "C:\\Users\\Jochen\\AppData\\Local\\Programs\\Julia-1.7.2\\share\\julia"

julia> projectdir()
"c:\\Users\\Jochen\\Documents\\GCF\\DSL"

julia> Base.active_project()
"c:\\Users\\Jochen\\Documents\\GCF\\DSL\\Project.toml"

Now when I type "dev /src/Agent"
I get the following:
ERROR: `/src/Agent` appears to be a local path, but directory does not exist

Perhaps this helps: I also would expect that if I go to the package manager, and type "generate src/dummy", I would get a new Project.toml in \GCF\DSL\src\dummy\. However, this is where the new Project.toml actually is generated:
C:\Users\Jochen\src\dummy\

Ultimately, I went with "pkg> dev --local Agents", which created a "dev" subfolder in the projectdir. This is pretty much what I wanted, I gather, but it doesn't seem to be the same as what is described in the Dr Watson docs.

**Comment by Datseris** [comment]
Have you changed your working directory to the project path? e.g., do `cd(projectdir())` ?

**Comment by Datseris** [comment]
https://juliadynamics.github.io/DrWatson.jl/dev/project/#Including-Julia-packages/modules-in-src-1

**Comment by jochenkrattenmacher** [comment]
oh yes I forgot to mention... I did that yes

**Comment by jochenkrattenmacher** [comment]
It's strange, I tried to recreate the same behavior for "generate /src/dummy" but this time a new folder got created at "C:/src/dummy" instead of "C:\Users\Jochen\src\dummy\"

**Comment by Datseris** [comment]
so you're doing exactly what is described here: https://juliadynamics.github.io/DrWatson.jl/dev/project/#Including-Julia-packages/modules-in-src-1  ? You go into project dir. Then you also `cd` into the same dir. And then you do the `dev src/Agents`. And it doesn't work? Are you sure?

**Comment by jochenkrattenmacher** [comment]
well it works now... thanks and sorry for the confusion. I am quite sure it didn't work before (my command history would indicate so), but well it wouldn't be the first time something started working after a simple restart
