### ISSUE TITLE
Provenance information for Plots.jl/PGFPlotsX.jl generated figures

### ISSUE THREAD

**Issue by bringuiers** [JuliaDynamics/DrWatson.jl#341]
I'm relatively new to [DrWatson.jl](https://github.com/JuliaDynamics/DrWatson.jl) and started using it for a project. I have several scripts  that generate `pgf/tikz` plots saved in a `tikz` file. This is done using [Plots.jl](https://github.com/JuliaPlots/Plots.jl) with the [PGFPlotsX.jl](https://github.com/KristofferC/PGFPlotsX.jl) backend. The `tikz` files are then used in a LaTeX document within the same DrWatson.jl project (i.e. in papers) and if I regenerate the `tikz` files the names are the same. 

The `tikz` files are tracked via git however there are many instances where I want to view the script and list of data that was used to generate the `tikz` file. Rather than searching the git tree to find this out, I was thinking of injecting within the `tikz` file LaTeX comments that contain the git information but also a replica of the script and a list of data files in order to facilitate quick inspection. In the past I've done this by running shell commands within a Julia script to inject git info and the script content, but my question is to whether or not there is a more 'DrWatsonian` way to achieve my goal or maybe I'm missing something trivial that I need to do.

**Comment by Datseris** [comment]
hi there, I am completely unfamiliar with tikz, but I'll try to help.

So, if I understood you correctly, you would like a way to use the `tag!` function for the `tikz` file, right? You can't use `tag!` directly, because it needs a dictionary, but wouldn't using https://juliadynamics.github.io/DrWatson.jl/dev/save/#DrWatson.@tag!  on an empty dict, and then simply extracting the dict's fields into the latex file do the trick? The same dict can contain the parameters you used. So, assuming that you have a julia file that generates the tikz plot, then I suggest:

```julia
d # dictionary with parameters for tikz plot
@tag!(d)

f = save_tikz_latex_file

fpr (key, val) in d
write_in_latex!(f, "key $(key) with val $(val)")
end
```

Or I didn't get what you want in the end?

**Comment by Datseris** [comment]
By the way, if you solve this request, please consider adding a section about it in our "Real World Usage" example page :)

**Comment by bringuiers** [comment]
Thanks for the quick reply. So I think,

> [@tag!(d)](https://juliadynamics.github.io/DrWatson.jl/dev/save/#DrWatson.@tagsave)

Is very close to what I want! Now I just need to put together my preferred way to implement

> write_in_latex!(f, "key $(key) with val $(val)")

If I get what I want I'll create a pull request for additions to [Real World Usage](https://juliadynamics.github.io/DrWatson.jl/dev/real_world/).

**Comment by Datseris** [comment]
`write_in_latex!` was a shortcut for reading in the latex file with Julia's Base read function, and then at the end of the line appending the lines as latex comments (i.e., prefaced with `%`). That's the simplest way I can think of. Perhaps we can make a nice function in DrWatson `append_to_file!` that appends a dictionary in a text file, with a given character as preface.

**Comment by bringuiers** [comment]
So this is my solution at the moment which is working the way I envisioned:

```julia
using DrWatson
using Plots; pgfplotsx()

"""
    used to insert a comment line at eof of a latex file.
""" function insert_latex_comment(file, string::String)
    open(file, "r+") do io
        readlines(io)
        @assert eof(io)
        mark(io)
        buf = IOBuffer()
        seekstart(buf)
        reset(io)
        write(io, "% "*strip(string,'%')*"\n";)
    end
end

DrWatson._wsave(filename,fig::Plots.Plot{Plots.PGFPlotsXBackend},d::Dict) = begin
    mkpath(dirname(filename));
    savefig(fig,filename)
    for (k,v) in d
        outstr = "$k => $v"
        insert_latex_comment(filename,outstr)
    end
end

"""
    method for Plots.Plots{Plots.PGFPlotsXBackend}

!!! note
    No safesave
""" DrWatson.tagsave(file, plot::Plots.Plot{Plots.PGFPlotsXBackend};
                                   gitpath=projectdir(),
                                   safe::Bool=DrWatson.readenv("DRWATSON_SAFESAVE", false),
                                   storepatch::Bool=DrWatson.readenv("DRWATSON_STOREPATCH", false),
                                   force=false, source=nothing, kwargs...
                                   ) = begin
     d = Dict("plotbackend"=>"Plots.PGFPlotsXBackend")
     d2 = tag!(d, gitpath=gitpath, storepatch=storepatch, force=force, source=source)
     if safe
        @error "Need to overload safe ave for PGFPlotsXBackend"
    else
        wsave(file,plot,d2; kwargs...)
    end
    return d2
end

x = range(0,4π,length=10);
y = sin.(x);

p = plot(x,y,label="function");

@tagsave("test.tikz",p);
```

This gives the following tikz output in file `test.tikz`:

```latex
\begin{tikzpicture}[/tikz/background rectangle/.style={fill={rgb,1:red,1.0;green,1.0;blue,1.0}, draw opacity={1.0}}, show background rectangle]
\begin{axis}[point meta max={nan}, point meta min={nan}, legend cell align={left}, legend columns={1}, title={}, title style={at={{(0.5,1)}}, anchor={south}, font={{\fontsize{14 pt}{18.2 pt}\selectfont}}, color={rgb,1:red,0.0;green,0.0;blue,0.0}, draw opacity={1.0}, rotate={0.0}}, legend style={color={rgb,1:red,0.0;green,0.0;blue,0.0}, draw opacity={1.0}, line width={1}, solid, fill={rgb,1:red,1.0;green,1.0;blue,1.0}, fill opacity={1.0}, text opacity={1.0}, font={{\fontsize{8 pt}{10.4 pt}\selectfont}}, text={rgb,1:red,0.0;green,0.0;blue,0.0}, cells={anchor={center}}, at={(1.02, 1)}, anchor={north west}}, axis background/.style={fill={rgb,1:red,1.0;green,1.0;blue,1.0}, opacity={1.0}}, anchor={north west}, xshift={1.0mm}, yshift={-1.0mm}, width={145.4mm}, height={99.6mm}, scaled x ticks={false}, xlabel={}, x tick style={color={rgb,1:red,0.0;green,0.0;blue,0.0}, opacity={1.0}}, x tick label style={color={rgb,1:red,0.0;green,0.0;blue,0.0}, opacity={1.0}, rotate={0}}, xlabel style={at={(ticklabel cs:0.5)}, anchor=near ticklabel, at={{(ticklabel cs:0.5)}}, anchor={near ticklabel}, font={{\fontsize{11 pt}{14.3 pt}\selectfont}}, color={rgb,1:red,0.0;green,0.0;blue,0.0}, draw opacity={1.0}, rotate={0.0}}, xmajorgrids={true}, xmin={-0.37699111843077515}, xmax={12.943361732789947}, xtick={{0.0,2.0,4.0,6.0,8.0,10.0,12.0}}, xticklabels={{$0$,$2$,$4$,$6$,$8$,$10$,$12$}}, xtick align={inside}, xticklabel style={font={{\fontsize{8 pt}{10.4 pt}\selectfont}}, color={rgb,1:red,0.0;green,0.0;blue,0.0}, draw opacity={1.0}, rotate={0.0}}, x grid style={color={rgb,1:red,0.0;green,0.0;blue,0.0}, draw opacity={0.1}, line width={0.5}, solid}, axis x line*={left}, x axis line style={color={rgb,1:red,0.0;green,0.0;blue,0.0}, draw opacity={1.0}, line width={1}, solid}, scaled y ticks={false}, ylabel={}, y tick style={color={rgb,1:red,0.0;green,0.0;blue,0.0}, opacity={1.0}}, y tick label style={color={rgb,1:red,0.0;green,0.0;blue,0.0}, opacity={1.0}, rotate={0}}, ylabel style={at={(ticklabel cs:0.5)}, anchor=near ticklabel, at={{(ticklabel cs:0.5)}}, anchor={near ticklabel}, font={{\fontsize{11 pt}{14.3 pt}\selectfont}}, color={rgb,1:red,0.0;green,0.0;blue,0.0}, draw opacity={1.0}, rotate={0.0}}, ymajorgrids={true}, ymin={-1.0438962181929405}, ymax={1.0438962181929405}, ytick={{-1.0,-0.5,0.0,0.5,1.0}}, yticklabels={{$-1.0$,$-0.5$,$0.0$,$0.5$,$1.0$}}, ytick align={inside}, yticklabel style={font={{\fontsize{8 pt}{10.4 pt}\selectfont}}, color={rgb,1:red,0.0;green,0.0;blue,0.0}, draw opacity={1.0}, rotate={0.0}}, y grid style={color={rgb,1:red,0.0;green,0.0;blue,0.0}, draw opacity={0.1}, line width={0.5}, solid}, axis y line*={left}, y axis line style={color={rgb,1:red,0.0;green,0.0;blue,0.0}, draw opacity={1.0}, line width={1}, solid}, colorbar={false}]
    \addplot[color={rgb,1:red,0.0;green,0.6056;blue,0.9787}, name path={6380dbfb-47e9-4361-97a2-5bb365842b81}, draw opacity={1.0}, line width={1}, solid]
        table[row sep={\\}]
        {
            \\
            0.0  0.0  \\
            1.3962634015954636  0.984807753012208  \\
            2.792526803190927  0.3420201433256689  \\
            4.1887902047863905  -0.8660254037844385  \\
            5.585053606381854  -0.6427876096865396  \\
            6.981317007977318  0.6427876096865391  \\
            8.377580409572781  0.8660254037844392  \\
            9.773843811168245  -0.342020143325668  \\
            11.170107212763709  -0.9848077530122081  \\
            12.566370614359172  -4.898587196589413e-16  \\
        }
        ;
    \addlegendentry {function}
\end{axis}
\end{tikzpicture}
% plotbackend => Plots.PGFPlotsXBackend
% gitcommit => 1c86e6029040614af911f902665262558e61d60b
% script => scripts/Test.jl#53
```

I had to overload `tagsave` because `tag!` requires `Dict`, so I construct a dummy one in `tagsave`.

A few things I would prefer:
- Probably be more useful if the info is at the beginning of the file.
- How to go about making overloads available across project, i.e., `DrWatson._wsave` in `src` that is a module with [reexport](https://github.com/simonster/Reexport.jl)

Any input on cleaner implementation of the above would be much appreciated.

**Comment by Datseris** [comment]
That is very good! Do you mind contributing a documentation PR then?

> How to go about making overloads available across project

That is, unfortunately, not possible without you publishing some package and using it. Due to the way method overload works in Julia, the only way to overload a method, such as `DrWatson._save`, is (1) to overload it "live" by literally running the function, or to do `using PackageX` where package `X` has the overloading code.

I am closing this as you seem to have reach a working result.
