### ISSUE TITLE
Dead link on documentation front page

### ISSUE THREAD

**Issue by Sciemon** [JuliaDynamics/DrWatson.jl#344]
On the introduction page there is a dead link:
"
If you want to see how DrWatson compares with other existing alternatives, please have a look at our paper in [Citing](https://juliadynamics.github.io/DrWatson.jl/dev/@ref).
"

**Comment by Datseris** [comment]
yeah it should be "Citation", do you mind doing a quick PR?

**Comment by Sciemon** [comment]
If I knew how to do it (I'm not yet the markdown expert) I would have created a PR in the first place.
