### ISSUE TITLE
Maybe add a warning initialize_project

### ISSUE THREAD

**Issue by fkrauer** [JuliaDynamics/DrWatson.jl#349]
Hi

I really love DrWatson, but I have a suggestion: 

If you do `initialize_project()`, any _existing_ directory with the **same** name will automatically be overwritten. I kind of expected there to be a warning or that the two directories might be integrated, but instead it was just overwritten. It's not a big deal in my case as I had a backup, but I would suggest you add a warning somewhere in the docs or on Github? This may be obvious to experienced users, but for beginners it's probably not so obvious. 

Thanks for all the great work! 
Best, Fabienne

**Comment by Datseris** [comment]
hi, this seems to be a bug, because the docs say:

![image](https://user-images.githubusercontent.com/19669089/174785405-5ceb8c71-a732-4368-b886-12b94bf2e737.png)

so, if your directory was not empty, you should have gotten an error. Can you confirm?

**Comment by fkrauer** [comment]
Hi George

I just checked and it seems I used `force = true` [😳](https://emojipedia.org/flushed-face/#:~:text=A%20yellow%20face%20with%20raised,admiration%2C%20affection%2C%20and%20excitement.) My mistake, sorry! 

I copied the command from the Tutorial without thinking much about the arguments: https://juliadynamics.github.io/DrWatson.jl/dev/workflow/

I'll close this, as is not an issue just an oversight on my part. 

Bw, Fabienne
