### ISSUE TITLE
Include a diff with the saved model run?

### ISSUE THREAD

**Issue by mauro3** [JuliaDynamics/DrWatson.jl#36]
When experimenting, I often edit the source-code, to check what changing a parameter does.  
I don't want to ~~check-in~~ commit this code as I'm just trying things out.
(Sure, I should refactor and make that a settable parameters, but life is too short.)  

Also, sometimes I just forget to ~~checkin~~ comit before starting a run.  So, how about storing a diff/patch  with the model results?  Just the output of `git diff` should be fine.

Reproduction would then be:
```
git checkout saved-sha
git apply stored-diff
julia -e ...
```

Edit: not sure where the "check-in" came from.  Probably a flash back to [svn](https://sliksvn.com/support/subversion-basics-using-check-out-update-check-in-commit/), probably because I recently cloned a svn repository...

**Comment by Datseris** [comment]
I must admit, I Don't understand what you are trying to suggest.... 

* What does "check-in" mean?
* Storing the diff, where?

**Comment by mauro3** [comment]
In `tagsave`, so it wouldn't just store the commit but in case of a dirty repo also the diff.  It would put it whereever `tagsave` puts the sha.

**Comment by mauro3** [comment]
This would address what is mentioned here https://discourse.julialang.org/t/drwatson-the-perfect-sidekick-to-your-scientific-inquiries/23241/9 by @kescobo.

**Comment by Datseris** [comment]
Ohhhhh now I see. Related with #35 which increases the amount of "source state" related data.

I don't know what is the best format for the dif though. How do you save it so that it is usable?

**Comment by Datseris** [comment]
Although I am skeptical: this functionality would support bad practices (i.e. asking to save a git commit when the repo is dirty).

**Comment by mauro3** [comment]
To save to a text file
```
git diff > some.diff
```
Not sure how to do it with LibGit but I'm sure it can be done.

To apply
```
git checkout saved-sha
git apply some.diff
```
So, if the diff is stored as a string, something like `write("some.diff", saveddiff)` would be the whole extent of the "apply"-interface.

**Comment by mauro3** [comment]
> (i.e. asking to save a git commit when the repo is dirty).

I'm not sure I follow.  Nothing is commited.

I think the interface for `tagsave` could be to error on a dirty repo, or if a keyword is given (`savediff=true`) then save the diff also (if the repo is dirty).

**Comment by Datseris** [comment]
Yeah this is fine, A PR for this would be appreciated, as I still don't know how to handle the diff and in what format to save it.

**Comment by Datseris** [comment]
#39 is relevant: adds more reproducibility information to the saved file. The only thing missing now is to implement the current suggestion which also adds the Git Diff. (easy to do with LibGit)

**Comment by Datseris** [comment]
@mauro3 can you please give some input about how could the proposal here be implemented?

**Comment by mauro3** [comment]
See the PR.  Let me know what you think.
