### ISSUE TITLE
GitReference should be LibGit2.GitReference

### ISSUE THREAD

**Issue by NicholasWMRitchie** [JuliaDynamics/DrWatson.jl#368]
I don't think that LibGit2 exports GitReference.
GitReference is used on line 308 of project_setup.jl.

`LibGit2.delete_branch(GitReference(repo, "refs/heads/$default"))` should probably be `LibGit2.delete_branch(LibGit2.GitReference(repo, "refs/heads/$default"))`

**Comment by Datseris** [comment]
ah thats why this doesnt work... can you open a PR?
