### ISSUE TITLE
Use a project name without a space in the examples in the documentation

### ISSUE THREAD

**Issue by KristofferC** [JuliaDynamics/DrWatson.jl#369]
When I see `@quickactivate "DrWatson Example"` it is quite confusing to me. It seems like something is done with the DrWatson.jl package AND the Example.jl package. If this was written as `"DrWatsonExample` or `DrWatson_Example` it would be clearer in my opinion.

**Comment by Datseris** [comment]
I agree! I had fixed that: https://github.com/JuliaDynamics/DrWatson.jl/blob/main/docs/src/workflow.jl#L24 but for whatever reason the dev docs weren't updated... Will look into it hopefully soon!

**Comment by Datseris** [comment]
Yes, I just changed that. It was like that since the dawn of time for this repo... Will have to figure out why the DEV build was not updated in the near future nevertheless.
