### ISSUE TITLE
Is there a way to leave a project?

### ISSUE THREAD

**Issue by ignace-computing** [JuliaDynamics/DrWatson.jl#378]
This is more like a question - sorry for that.

Is there a way to leave a project (in order to go to another project)?
Motivation: it can be nice to be working on several projects at the same time.

If yes, it would be nice to add this to the docs, IMHO.
If no, this post can be considered a feature request.

Thanks!

**Comment by ignace-computing** [comment]
Ok, I think I found it.
One just needs to move to another folder which hosts a project (for instance using the function `cd`) and then one can activate the other project.
Should I add this to the docs or is this not worth it?

**Comment by Datseris** [comment]
Nope, it's not worth it. It is also ambiguous what you mean by "leave project". May mean several different things: changing the directory of a project, activating another project, deleting a project, renaming a project,.......
