### ISSUE TITLE
Slashes removed in #380

### ISSUE THREAD

**Issue by karajan9** [JuliaDynamics/DrWatson.jl#384]
**Describe the bug**
PR #380 removed a trailing slash from `projectdir` and, by extension, `datadir` etc. This is breaking for me, since my paths aren't valid anymore, while before they were.

**Minimal Working Example**
```
datadir("folder/")
Expected:
".../data/folder/"
Currently:
".../data/folder"
```

Since this breaks previously working code (in a patch release no less, 2.12.1 to 2.12.2) I believe this should be reverted.

**Comment by Datseris** [comment]
Yes, I'll fix this. Hm PR#380 was weird now that I think about it. the author made the change necessary to fix the original issue #181, but _also_ changed the `projectdir` behavior. The `projectdir` change was not necessary as far as  I can tell.
