### ISSUE TITLE
"verbose &&" before  @info "Scanning folder $folder for result files."

### ISSUE THREAD

**Issue by yp51md** [JuliaDynamics/DrWatson.jl#388]
Sometimes I need to import several folders in a loop, every time I call `collect_results()`, Info like "@Info: Scanning folder" will be printed. It is kind of annoying. I am wondering if the "verbose &&" can be put in front of all the `@info`?

The `@info`:
https://github.com/JuliaDynamics/DrWatson.jl/blob/a9a238333a883935f6504382da28dc815fdec988/src/result_collection.jl#LL115C54-L115C54

<img width="318" alt="Screenshot 2023-05-08 at 17 20 12" src="https://user-images.githubusercontent.com/41810562/236787020-d691b8b4-d97c-4729-972e-07c8f3e4d536.png">

**Comment by Datseris** [comment]
yes go ahead and do the pr!
