### ISSUE TITLE
Default project should include test directory

### ISSUE THREAD

**Issue by jessebett** [JuliaDynamics/DrWatson.jl#40]
Encourage scientists to write unit test for `src`!

**Comment by Datseris** [comment]
To implement this one has to : 
1. Add the path here: https://github.com/JuliaDynamics/DrWatson.jl/blob/master/src/project_setup.jl#L118
2. Document it in this text file: https://github.com/JuliaDynamics/DrWatson.jl/blob/master/src/defaults/project_structure.txt

I would suggest also making a default `runtests.jl` file.

This is a quite easy issue, perhaps @jessebett its your chance to become a contributor? ;)
