### ISSUE TITLE
Package Extension for LanguageServer.jl

### ISSUE THREAD

**Issue by nateybear** [JuliaDynamics/DrWatson.jl#419]
**Is your feature request related to a problem? Please describe.**
When I use DrWatson and LanguageServer together, LanguageServer does not follow my paths for includes for `srcdir`, `scriptsdir`, etc. Hence my code is riddled with "missing references" and this annoys me.

**Describe the solution you'd like**
Create a package extension that is loaded if `StaticLint` is present. (This is the actual package that does the `include` resolution.) It should just require patching [this function](https://github.com/julia-vscode/StaticLint.jl/blob/d5144144ad26a3a5e04dc20bea7ee98bed2178b5/src/StaticLint.jl#L348), which is possible through type piracy. Hopefully it is not too much of a lift, and I can provide a pull request at some point when I have time.

**Describe alternatives you've considered**
My alternative to avoid these missing references from the language server is to not use DrWatson. I really like project-relative paths though, so this is a suboptimal solution.

**Comment by Datseris** [comment]
You seem to know how to solve this issue, perhaps you can open a PR to do so? It is okay if you limit Julia version to 1.9+, as 1.10 becomes the new LTS.

**Comment by nateybear** [comment]
Sure, I can look into it when I have time.

**Comment by nateybear** [comment]
@Datseris I opened an issue in LanguageServer asking about if they load userland code, but they don't. Since they don't see these path functions as important enough to include in the language server, there's no way to get this feature implemented. Closing unfortunately ☹️

**Comment by Datseris** [comment]
Can you link the issue please?

**Comment by nateybear** [comment]
github.com/julia-vscode/LanguageServer.jl/issues/1309

**Comment by Datseris** [comment]
So, if I understood this issue correctly, they claim that if you replace `include(srcdir(...)` with `include(joinpath(@__DIR__, "../../../ ...))` they LS would work? 

Is this first of all true? Does `include` with `joinpath` solve this? 

But, even if it was, the whole point of `projectdir` is that you don't have to guess how many `../.../.../.../` you have to write to go into the project root directory.

**Comment by Datseris** [comment]
I've opened an issue at Pkg.jl: https://github.com/JuliaLang/Pkg.jl/issues/3985 . We can see if they think it is useful or they have the same impression as the VSCode developers. Perhaps it can go into Pkg directly.

**Comment by nateybear** [comment]
Thanks for the update. Exposing `active_project` won't entirely fix the issue as the [source](https://github.com/julia-vscode/StaticLint.jl/blob/d5144144ad26a3a5e04dc20bea7ee98bed2178b5/src/StaticLint.jl#L348) does not expand function calls. So we would still need to talk to the VSCode folks about supporting `active_project` as well as `dirname`. IMO it's not very ergonomic to have `include(joinpath(dirname(active_project()), "src", "foo.jl"))` sprinkled everywhere either—having a convenience function like `projectdir` and friends really seems like the solution. I don't necessarily feel like I'm in a place to push that with the Pkg folks though.
