### ISSUE TITLE
How to name a project with the ".jl" format

### ISSUE THREAD

**Issue by martinmestre** [JuliaDynamics/DrWatson.jl#426]
Hi developers,
thank you very much for your package. I have used it in the past and found it very useful. 
Now I would like to name my local and github repo as `Name.jl`, but the directory be called just `Name` and 
to be able to activate it by doing:
 `@quickactivate :Name`
instead of 
`@quickactivate :Name.jl`.
I have not managed to do so. Is it possible?
Thank you very much.

**Comment by Datseris** [comment]
Simply past the name with ".jl" in the second argument of the initialize project function!

You won't be able to use `@quickactivate :Name.jl` though, as you can't use `.` within a macro.

Speaking from experience, it is odd that a project name is ending with `.jl`. Typically it is only the github repo that ends with .jl (and the actual julia source code files of course)>
