### ISSUE TITLE
If using a non-default template for the project setup, is it possible to change the functions datadir(), srcdir(), etc ?

### ISSUE THREAD

**Issue by martinmestre** [JuliaDynamics/DrWatson.jl#430]
I am interested in knowing if it possible and how.
This issue happens because I am trying to combine DrWatson with [ShowYourWork](https://show-your.work/en/latest/layout/), the latter having a different directory setup. For example, I would like to have the functions corresponding to the following structure:
`srcdir() `-> src/ 
`scriptsdir() `-> src/scripts/
`datadir()` -> src/data/
and similary for:
src/notebooks
src/tex
src/static

Thanks!

**Comment by Datseris** [comment]
You would have to overwrite the function definitions on loadup by doing `DrWatson.scriptsdir(args...) = srcdir("scripts", args...)`. But this you would have to do every time. There isn't any other way besides altering the source code of DrWatson itself, or creating brand new functions.

**Comment by martinmestre** [comment]
Thanks! Then it is easier as I am doing now which keeps DrWatson's default instead of showyourwork's.
I leave a message for future user: it is importante that the tex dir is here:
src/tex.
