### ISSUE TITLE
Convenience signature datadir(args...)

### ISSUE THREAD

**Issue by JonasIsensee** [JuliaDynamics/DrWatson.jl#47]
I propose a single one-liner 
`DrWatson.datadir(arg1, args...) = joinpath(datadir(), arg1, args...)`

This will allow the following common pattern to be shorter.
```
path = joinpath(datadir(), "results", "mymodel")
path = datadir("results", "mymodel")
```

The following 
`datadir(args...) = joinpath(datadir(), args...)`
causes a stackoverflow because `args...` may also be no arguments at all.

**Comment by Datseris** [comment]
Sounds good. a comment

This interface should be applied to all functions `projectdir, datadir, srcdir,...` etc. This can be done with a loop over the function names and `@eval`.

**Comment by Datseris** [comment]
However it should be said that Julia can chain paths with `/` irrespectively of the operating system. so for example
```
datadir()*"light/case1/subfolder/data.jld"
```
works, and is significantly cleaner than
```
datadir("light", "case1", "subfolder", "data.jld")
```

(of course this doesn't prevent the suggested API to be implemented, since it does not conflict with what I showed)

**Comment by tamasgal** [comment]
I just wanted to propose a very similar interface ;)

**Comment by Datseris** [comment]
@tamasgal thanks for the input! The suggestion here is super-easy to implement and we are always looking for more people to get the "contributor" status :) 

If you want to implement it, I cannot imagine it taking more than 20 minutes for you

**Comment by Datseris** [comment]
Thanks @tamasgal for showing that my naive approach of just multiplying `"\"` isn't always healthy programming-wise. Thankfully #64 solves everything (by breaking everything :D )
