### ISSUE TITLE
Add OS-specific files to .gitignore

### ISSUE THREAD

**Issue by cherbigmet** [JuliaDynamics/DrWatson.jl#57]
I think that the default .gitignore file DrWatson generates should include the following OS-specific patterns:

.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

Also, ignore .ipynb_checkpoints for Jupyter Notebooks.
See 
https://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository
https://stackoverflow.com/questions/36306017/should-ipynb-checkpoints-be-stored-in-git

**Comment by cherbigmet** [comment]
Also, in case somebody wants to use Documenter.jl, it should ignore docs/build

**Comment by asinghvi17** [comment]
If you want to make a PR you can edit this file:

https://github.com/JuliaDynamics/DrWatson.jl/blob/master/src/defaults/gitignore.txt

**Comment by Datseris** [comment]
yeah a pr would make you a contributor, which is cool!!!

**Comment by cherbigmet** [comment]
At the moment, my company does not have a policy on open-source contributions, but management is looking into it. For now I don't want to patch something and risk it turning into an intellectual property dispute, causing problems for everyone.

**Comment by asinghvi17** [comment]
I was thinking we could do OS specific editing of the gitignore file at build as well, for MacOS especially.

**Comment by Datseris** [comment]
I think the complexity and first-run-time penalty of adding a build stage is not really worth it. There is almost zero drawback in adding the OS specific files for all users given that most of them start with `.`

**Comment by Datseris** [comment]
But maybe I am wrong!

**Comment by cherbigmet** [comment]
I think it would be simplest to just hardcode all of the known OS-specific filenames into the gitignore file. That way it doesn't matter who checks it out on what or if they migrate to a new system.

**Comment by asinghvi17** [comment]
@cherbigmet, @Datseris: I took it a step too far, completely reworked the gitignore file...you can see the changes in the PR #58.  I took a lot of data from gitignore.io, and mentioned it at the bottom of the file.

**Comment by cherbigmet** [comment]
Wow! Well, if it passes, then it definitely takes care of my concerns, at which point, feel free to close this ticket.
