### ISSUE TITLE
Preferred  way to develop source

### ISSUE THREAD

**Issue by jessebett** [JuliaDynamics/DrWatson.jl#62]
@Datseris could you give an example for how you set up your `src` for a project. 

I had some trouble following the [REPL-Based Workflow](https://docs.julialang.org/en/v1/manual/workflow-tips/#REPL-based-workflow-1). In which I created a module file in `src` which includes other source files. Then in a script I would `include(srcdir()*"module.jl")` and `using .ModuleName` which worked fine. However, developing wasn't great because changes to the source files or module would not be updated by Revise, and reloading them got conflict warnings.

Instead I'm currently pushing the `src` directory to my `LOAD_PATH` and using the module in a usual way. This works well with Revise, but isn't really nice.

You mentioned that a better solution would be to `]dev`? Is this in the `src` directory or the entire project directory? I probably misunderstand what `]dev` does, but I thought it needed to be a package (though I'm not sure what that entails).

**Comment by asinghvi17** [comment]
You can dev any project with a Project.toml that has a name, UUID, and src/ProjectName.jl.  That will play well with Revise AFAIK - it just informs Julia that the package will change.

**Comment by jessebett** [comment]
Okay, but following the default setup from the DrWatson docs my `Project.toml` has no UUID. So I cannot `]dev .`. Any idea there?

**Comment by jessebett** [comment]
Further, if I get a `uuid` from `Pkg.generate` and put it in there, I cannot `]dev .` because, understandably, `ERROR: Cannot develop package with same name or uuid as the project`.

**Comment by asinghvi17** [comment]
Switch to the global env and then dev it?  Should work then.

**Comment by jessebett** [comment]
Switch to the global env, dev it, then switch back? Or are you proposing I work inside the global env which would defeat the whole purpose of working in a project, no?

**Comment by jessebett** [comment]
And that doesn't address that `Project.toml` has no UUID by default, so this is likely not the intended method to develop the project.

I already have a patch (which is to push the `srcdir` to the  `LOAD_PATH` but I'm trying to learn the correct/intended way to do this, instead of workarounds. It seems to me that if I have to manually generate a UUID, add it to the `Project.toml` and `]dev` from outside my project env, then something isn't right.

The main consideration is that this should be easily reproducible. That I should be able to just hand this repo to someone else and have it work. That definitely won't be easy if there needs to be messing with `LOAD_PATH` or environments to get the scripts to work with `using MyModule`...

**Comment by Datseris** [comment]
Hi @jessebett , thanks for opening this. I will now address your questions, and I hope I can resolve your confusions. Before that though, I need to stress the following point:

* DrWatson is not a package to help you develop a Julia package. It is a package to help you manage your scientific project, which is represented by a Julia project. Notice that a Julia project does not have to be a Julia package. (But by definition, a Julia package is always a Julia project).

---

As you have already mentioned: 

> And that doesn't address that Project.toml has no UUID by default, so this is likely not the intended method to develop the project.

That is correct and is on purpose. The `Project.toml` file represents your scientific project, not a Julia package. What I assume you want to do is _include a Julia package you are developing_ inside your own project.

This is how I do it, and how I suggest you do it:

![image](https://user-images.githubusercontent.com/19669089/60291901-48248e00-991c-11e9-9531-998f64f0314d.png)

Above, `kwant_graphene`, is my scientific project, which is also a Julia project, and is initialized by DrWatson. I use DrWatson throughout this project. In my `src` folder you will first see that I have some casual script files that define core functions, e.g. `HusimiPlotting.jl`. These files I normally `include` in all my script.

What you will see is that inside my project's `src` folder I also have two Julia **packages**, `Chebyshev, HusimiFunctions`. These are proper Julia packages in every sense of the way. I develop them normally and include them in my project normally using `using HusimiFunctions` and update them in real time with e.g. Revise. To create this setup you need the following steps:

1. Active your project that uses DrWatson.
2. Change directory to the project's `src` folder.
3. Go into package mode and initialize a package with the name that you want (in my case `HusimiFunctions`)
4. `dev` the local path to `HusimiFunctions` using the package manager , e.g. `dev /path/to/project/src/HusimiFunctions`. **It is strongly recommended to `dev` this using local paths instead**, see this PR that will be merged soon: https://github.com/JuliaLang/Pkg.jl/pull/1215

That is it.

If this solves your concerns please let me know and I will put it into DrWatson's documentation as is.

**Comment by Datseris** [comment]
@jessebett can you please tell me if this was okay for you?

**Comment by jessebett** [comment]
Hi @Datseris. Yes, you are correct that my issue was conflating packages and projects. I've compartmentalized the package into its own sub-directory as you've suggested and it works for me. I agree that this could be worth highlighting in the docs.

**Comment by Datseris** [comment]
Thanks, will do so soon! :)

**Comment by asinghvi17** [comment]
Might also be worth using git submodules?  Could be too much hassle though...
