### ISSUE TITLE
savename digits respect "1e-6" syntax

### ISSUE THREAD

**Issue by jessebett** [JuliaDynamics/DrWatson.jl#63]
If I specify an argument like `:lr=>1e-5` I would like `savename` to not attempt to round this. At the moment this is beyond the default `digits=4` and gets saved as `lr=0`. 

Is it easy to distinguish floats written as `1e-2` from `0.01`? If so, can the former be preserved in the savename?

**Comment by sebastianpech** [comment]
I don't think that this is possible. `1e-5` is just a different method of defining a float, so the calling function justs sees the float and not the used notation. 

Alternatively we could check the rounding results in `savename` and if it's `0.0` instead display `digits` significant digits.

Julia internally uses the [grisu algortihm](https://github.com/JuliaLang/julia/blob/55e36cc308b66d3472990a06b2797f9f9154ea0a/base/grisu/grisu.jl) for printing floating point numbers. 
There is `Base.Grisu.print_shortest` which returns the shortest possible representation of a floating point number while alllowig parsing the resulting string to the same number.

**Comment by Datseris** [comment]
Alright, I don't see this getting into 1.0, but this can only be accepted as a non breaking change. Here is my proposal: 

Implement a keyword argument `scientific = nothing`. If `nothing`, the behavior is as is. If it is an integer, the result is plotted in scientific notation, with `scientific` significant digits being displayed. E.g. `0.00123` becomes `123e-5` if `scientific` is 3 or more, but if e.g. `scientific` is 1, then it becomes `1e-3`.
