### ISSUE TITLE
Path separators

### ISSUE THREAD

**Issue by tamasgal** [JuliaDynamics/DrWatson.jl#66]
I think it would be better to encourage the users the use of `joinpath` instead of `*` and hard coded OS dependent path separators.

At this moment the path accessor functions like `datadir()`, `srcdir()` etc. are designed to always return a path with a leading `/` as path separator just for convenience so that the users can type `datadir()*"whatever"` to generate a path to `whatever`.

Given that DrWatson's primary design goal is reproducibility, I think it would be better to switch to a more generic approach.

I already filed this pull request which was merged (thanks!): https://github.com/JuliaDynamics/DrWatson.jl/pull/64

So we now have things like `datadir("whatever", "path", "you", "want")` yielding a path to `whatever:path:you:want` with correct path separators. Also the `projectdir()` was extended with a method to concatenate the path-parts correctly.
However, there is still this leading `/` everywhere, which of course causes errors, especially when users get used to it.

What do you think?

**Comment by Datseris** [comment]
Hey,

yes you are absolutely right. I think that was a sloppy implementation by me. Let's fix this in #64, thanks! :)

**Comment by Datseris** [comment]
I'll take care to make this transparent in the docs and promote `joinpath` as much as possible!

**Comment by Datseris** [comment]
Closed in #64
