### ISSUE TITLE
update to new API of DataFrames.jl

### ISSUE THREAD

**Issue by JonasIsensee** [JuliaDynamics/DrWatson.jl#68]
DataFrames.jl has released a new version.
Functions like `collect_results` throw lots of deprecation warnings now.

We should update this before errors start showing up.

**Comment by Datseris** [comment]
:(

**Comment by tamasgal** [comment]
Can you provide some MWEs? I can try to help out...

**Comment by JonasIsensee** [comment]
Thanks, but don't worry about it.
Producing a MWE is probably more work than fixing it myself.
I'll get around to it eventually.
