### ISSUE TITLE
Move DrWatson to JuliaPhysics?

### ISSUE THREAD

**Issue by crstnbr** [JuliaDynamics/DrWatson.jl#73]
It seems to me that DrWatson would fit more into JuliaPhysics, revolving around general physics packages, than into JuliaDynamics. After all, it has nothing to do with dynamical systems.

What do you guys think about moving the package over?

**Comment by Datseris** [comment]
It doesn't fit to neither unfortunately... If there was an org "JuliaScience" it could make sense.

Even if 
> After all, it has nothing to do with dynamical systems.

is true, it also has nothing to do with physics either. At the moment the benefit of it staying here is that I am the owner of the repo, and I am also the lead developer. 

Does someone from JuliaPhysics wants to contribute to DrWatson? Then I could reconsider.

**Comment by Datseris** [comment]
Will re-open this after contributions of the potential new owners have been done. Until then it makes no sense in my eyes.
