### ISSUE TITLE
Keyword arguments for tag! and tagsave

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DrWatson.jl#84]
The arguments of `tag!` and `tagsave` have become quite extensive. Maybe it is time to define keyword-based versions of these functions. This is very easy and also non-breaking.

Here is where is `tag!` defined: https://github.com/JuliaDynamics/DrWatson.jl/blob/master/src/saving_tools.jl#L125

I don't really know how keywords work with macros, so I don't know how `@tagsave` can be affected.

**Comment by mauro3** [comment]
> I don't really know how keywords work with macros, so I don't know how @tagsave can be affected.

You got to be a bit careful because `:(a = 1)` parses as an `Expr(:=,:a,1)` whereas for kws you need a `Expr(:kw, :a, 1)`. So some extra processing is probably needed but nothing too tricky.

**Comment by sebastianpech** [comment]
@Datseris you mean additional kw-methods for `tag! `and `tagsave`? So one should still be able to use the non-kw version?

**Comment by Datseris** [comment]
yeap, because this is the only way to make it non-breaking (since we are now in 1.0! :) )

**Comment by sebastianpech** [comment]
Thought so. Kinda tricky to not get warnings, but I figured it out. Will make a PR tomorrow.
