### ISSUE TITLE
Add julia-compat line to initialize_project

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DrWatson.jl#91]
The function `initialize_project` generates a project folder and structure. Then the `Project.toml` file is further edited here : 

https://github.com/JuliaDynamics/DrWatson.jl/blob/c25df1d7f7ea5cc2b9834a020aa7369ecc658e79/src/project_setup.jl#L211-L216

In this part of the code we must add this:
```
[compat]
julia = "vx.y.z"
```
to be written in the Project.toml file. `x.y.z` should be the same as major.minor version of Julia that called `initialize_project`, which is of course simply `string(VERSION)`

**Comment by pmk21** [comment]
Could I take this up?

**Comment by Datseris** [comment]
Of course! @pmk21
