### ISSUE TITLE
.gitignore generated with initialize_project is write protected by default

### ISSUE THREAD

**Issue by IsakFalk** [JuliaDynamics/DrWatson.jl#98]
Hi, I'm on Arch linux,

After initialising a project using the `initialize_project` function I get a `.gitignore` file that is write protected for me (I have to use `sudo` to change it).

Is this the intended outcome? It breaks with what cookiecutter does for example.

**Comment by Datseris** [comment]
No this was not the intended behavior, I count this as a bug. Should be easy to fix by simply changing the permission we call `write` with.

**Comment by sebastianpech** [comment]
Hmm. But `.gitignore` is just copied from the defaults folder. @IsakFalk can you check the file modes set on`src/defaults/gitignore.txt`.

**Comment by Datseris** [comment]
@IsakFalk bump.

**Comment by Datseris** [comment]
@IsakFalk or anyone else, if you can reproduce then post it here. Until then, this is closed.

**Comment by sebastianpech** [comment]
I ran into the same issue yesterday. Don't know why it hasn't showed up until now, but I can reproduce it. Will investigate it tomorrow.

**Comment by Datseris** [comment]
Thanks for having a look. on Windows I couldn't reproduce.

**Comment by sebastianpech** [comment]
This is actually a fun one again. So the error only occurs if you don't use a DrWatson version that was added with `dev`.

The version added with `add`:
```
-r--r--r--   1 spech  staff  6242 Nov  3 14:29 gitignore.txt
-r--r--r--   1 spech  staff    33 Nov  3 14:29 intro.jl
-r--r--r--   1 spech  staff  1772 Nov  3 14:29 project_structure.txt
-r--r--r--   1 spech  staff    28 Nov  3 14:29 runtests.jl
```

The version added with `dev`:
```
-rw-r--r--   1 spech  staff  6242 Jul 18 16:39 gitignore.txt
-rw-r--r--   1 spech  staff    33 Jul 18 16:39 intro.jl
-rw-r--r--   1 spech  staff  1772 Oct  7 14:53 project_structure.txt
-rw-r--r--   1 spech  staff    28 Jul 18 16:39 runtests.jl
```

So doing a `chmod` after copying should fix this.
